/**
 * lib/ortografia/bank.ts — §6.5
 *
 * Banco de preguntas de ortografía para Guardia Civil.
 * Todas las respuestas correctas siguen las normas RAE vigentes.
 *
 * Mínimo 220 ítems distribuidos en 9 categorías.
 */

import type { OrtografiaItem } from './types'

// ─── ACENTUACIÓN (~35 ítems) ────────────────────────────────────────────────

const ACENTUACION: OrtografiaItem[] = [
  // Dificultad 1: esdrújulas y agudas claras
  {
    categoria: 'acentuacion',
    enunciado: 'Señale la palabra CORRECTAMENTE acentuada:',
    opciones: ['medico', 'médico', 'medicó', 'mèdico'],
    correcta: 1,
    explicacion: 'Esdrújula: todas las esdrújulas llevan tilde (RAE, §3.1).',
    dificultad: 1,
  },
  {
    categoria: 'acentuacion',
    enunciado: 'Señale la palabra CORRECTAMENTE acentuada:',
    opciones: ['telefono', 'telefoño', 'teléfono', 'telefóno'],
    correcta: 2,
    explicacion: 'Esdrújula: «teléfono» lleva tilde en la antepenúltima sílaba (RAE, §3.1).',
    dificultad: 1,
  },
  {
    categoria: 'acentuacion',
    enunciado: 'Señale la palabra CORRECTAMENTE acentuada:',
    opciones: ['exámen', 'examen', 'examén', 'èxamen'],
    correcta: 1,
    explicacion: 'Llana terminada en -n: las llanas terminadas en vocal, -n o -s NO llevan tilde (RAE, §3.2).',
    dificultad: 1,
  },
  {
    categoria: 'acentuacion',
    enunciado: 'Señale la palabra CORRECTAMENTE acentuada:',
    opciones: ['arbol', 'árbol', 'arbòl', 'arból'],
    correcta: 1,
    explicacion: 'Llana terminada en consonante distinta de -n o -s: lleva tilde (RAE, §3.2).',
    dificultad: 1,
  },
  {
    categoria: 'acentuacion',
    enunciado: 'Señale la palabra CORRECTAMENTE acentuada:',
    opciones: ['cancion', 'cáncion', 'canción', 'cancìon'],
    correcta: 2,
    explicacion: 'Aguda terminada en -n: las agudas terminadas en vocal, -n o -s llevan tilde (RAE, §3.3).',
    dificultad: 1,
  },
  {
    categoria: 'acentuacion',
    enunciado: 'Señale la palabra CORRECTAMENTE acentuada:',
    opciones: ['lápiz', 'lapiz', 'lapíz', 'làpiz'],
    correcta: 0,
    explicacion: 'Llana terminada en -z (consonante distinta de -n, -s): lleva tilde (RAE, §3.2).',
    dificultad: 1,
  },
  {
    categoria: 'acentuacion',
    enunciado: 'Señale la palabra CORRECTAMENTE acentuada:',
    opciones: ['clasico', 'clásico', 'clasíco', 'clàsico'],
    correcta: 1,
    explicacion: 'Esdrújula: siempre lleva tilde (RAE, §3.1).',
    dificultad: 1,
  },
  {
    categoria: 'acentuacion',
    enunciado: 'Señale la palabra CORRECTAMENTE acentuada:',
    opciones: ['café', 'cafe', 'cafè', 'càfe'],
    correcta: 0,
    explicacion: 'Aguda terminada en vocal: lleva tilde (RAE, §3.3).',
    dificultad: 1,
  },
  {
    categoria: 'acentuacion',
    enunciado: 'Señale la palabra CORRECTAMENTE acentuada:',
    opciones: ['automovil', 'automóvil', 'autómovil', 'automovíl'],
    correcta: 1,
    explicacion: 'Llana terminada en -l (consonante distinta de -n, -s): lleva tilde (RAE, §3.2).',
    dificultad: 1,
  },
  {
    categoria: 'acentuacion',
    enunciado: 'Señale la palabra CORRECTAMENTE acentuada:',
    opciones: ['plátano', 'platano', 'platáno', 'platanó'],
    correcta: 0,
    explicacion: 'Esdrújula: siempre lleva tilde (RAE, §3.1).',
    dificultad: 1,
  },
  // Dificultad 2: diacríticos e hiatos
  {
    categoria: 'acentuacion',
    enunciado: '¿Cuál de las siguientes oraciones usa CORRECTAMENTE la tilde diacrítica?',
    opciones: [
      'Tú libro está en la mesa',
      'Tu libro está en la mesa',
      'Tu libro esta en la mesa',
      'Tú libro esta en la mesa',
    ],
    correcta: 1,
    explicacion: '«Tu» posesivo no lleva tilde; «tú» pronombre personal sí. «Está» (verbo) lleva tilde (RAE, §3.4.1).',
    dificultad: 2,
  },
  {
    categoria: 'acentuacion',
    enunciado: '¿Cuál de las siguientes oraciones usa CORRECTAMENTE la tilde diacrítica?',
    opciones: [
      'El sabe la respuesta',
      'Él sabe la respuesta',
      'Èl sabe la respuesta',
      'Êl sabe la respuesta',
    ],
    correcta: 1,
    explicacion: '«Él» pronombre personal lleva tilde diacrítica para diferenciarlo de «el» artículo (RAE, §3.4.1).',
    dificultad: 2,
  },
  {
    categoria: 'acentuacion',
    enunciado: '¿Cuál de las siguientes oraciones usa CORRECTAMENTE la tilde diacrítica?',
    opciones: [
      'No se si vendrá mañana',
      'No sé si vendrá mañana',
      'No sè si vendrá mañana',
      'No se sí vendrá mañana',
    ],
    correcta: 1,
    explicacion: '«Sé» verbo saber lleva tilde diacrítica para diferenciarlo de «se» pronombre (RAE, §3.4.1).',
    dificultad: 2,
  },
  {
    categoria: 'acentuacion',
    enunciado: '¿Cuál de las siguientes oraciones usa CORRECTAMENTE la tilde diacrítica?',
    opciones: [
      'Quiero más te, por favor',
      'Quiero mas té, por favor',
      'Quiero más té, por favor',
      'Quiero màs tè, por favor',
    ],
    correcta: 2,
    explicacion: '«Más» adverbio de cantidad y «té» sustantivo llevan tilde diacrítica (RAE, §3.4.1).',
    dificultad: 2,
  },
  {
    categoria: 'acentuacion',
    enunciado: 'Señale la palabra CORRECTAMENTE acentuada:',
    opciones: ['pais', 'país', 'païs', 'paìs'],
    correcta: 1,
    explicacion: 'Hiato de vocal cerrada tónica + abierta: la cerrada lleva tilde independientemente de las reglas generales (RAE, §3.4.2).',
    dificultad: 2,
  },
  {
    categoria: 'acentuacion',
    enunciado: 'Señale la palabra CORRECTAMENTE acentuada:',
    opciones: ['raiz', 'ráiz', 'raíz', 'raìz'],
    correcta: 2,
    explicacion: 'Hiato: la vocal cerrada tónica (í) lleva tilde aunque la palabra sea aguda acabada en -z (RAE, §3.4.2).',
    dificultad: 2,
  },
  {
    categoria: 'acentuacion',
    enunciado: 'Señale la palabra CORRECTAMENTE acentuada:',
    opciones: ['baul', 'bául', 'baúl', 'baùl'],
    correcta: 2,
    explicacion: 'Hiato de vocal abierta + cerrada tónica: la cerrada lleva tilde (RAE, §3.4.2).',
    dificultad: 2,
  },
  {
    categoria: 'acentuacion',
    enunciado: '¿Cuál de las siguientes oraciones es CORRECTA?',
    opciones: [
      'Sí, quiero ir, mas no puedo',
      'Si, quiero ir, más no puedo',
      'Sí, quiero ir, más no puedo',
      'Si, quiero ir, mas no puedo',
    ],
    correcta: 0,
    explicacion: '«Sí» afirmativo lleva tilde; «mas» conjunción adversativa (equivale a «pero») NO lleva tilde (RAE, §3.4.1).',
    dificultad: 2,
  },
  {
    categoria: 'acentuacion',
    enunciado: '¿Cuál de las siguientes oraciones usa CORRECTAMENTE la tilde?',
    opciones: [
      'Espero que dé su aprobación',
      'Espero que de su aprobación',
      'Espero que dè su aprobación',
      'Espero que dê su aprobación',
    ],
    correcta: 0,
    explicacion: '«Dé» verbo dar lleva tilde diacrítica para diferenciarlo de «de» preposición (RAE, §3.4.1).',
    dificultad: 2,
  },
  {
    categoria: 'acentuacion',
    enunciado: 'Señale la palabra CORRECTAMENTE acentuada:',
    opciones: ['oído', 'oido', 'óido', 'oidó'],
    correcta: 0,
    explicacion: 'Hiato: vocal cerrada tónica (í) + vocal abierta. La cerrada tónica siempre lleva tilde (RAE, §3.4.2).',
    dificultad: 2,
  },
  // Dificultad 3: monosílabos sin tilde, adverbios en -mente
  {
    categoria: 'acentuacion',
    enunciado: '¿Cuál de las siguientes palabras NO lleva nunca tilde?',
    opciones: ['fue', 'más', 'él', 'sé'],
    correcta: 0,
    explicacion: '«Fue» es monosílabo sin par diacrítico: nunca lleva tilde. Desde la Ortografía de 2010, la RAE lo confirma (RAE, §3.4.3).',
    dificultad: 3,
  },
  {
    categoria: 'acentuacion',
    enunciado: '¿Cuál de las siguientes palabras NO lleva nunca tilde?',
    opciones: ['té', 'dio', 'dé', 'tú'],
    correcta: 1,
    explicacion: '«Dio» es monosílabo sin par diacrítico: nunca lleva tilde (RAE, §3.4.3).',
    dificultad: 3,
  },
  {
    categoria: 'acentuacion',
    enunciado: '¿Cuál de las siguientes palabras NO lleva nunca tilde?',
    opciones: ['sí', 'vio', 'más', 'él'],
    correcta: 1,
    explicacion: '«Vio» es monosílabo sin función diacrítica: nunca lleva tilde (RAE, §3.4.3).',
    dificultad: 3,
  },
  {
    categoria: 'acentuacion',
    enunciado: 'Señale la palabra CORRECTAMENTE acentuada:',
    opciones: ['fácilmente', 'facilmente', 'facilménte', 'fàcilmente'],
    correcta: 0,
    explicacion: 'Adverbios en -mente conservan la tilde del adjetivo base: fácil → fácilmente (RAE, §3.3.4).',
    dificultad: 3,
  },
  {
    categoria: 'acentuacion',
    enunciado: 'Señale la palabra CORRECTAMENTE acentuada:',
    opciones: ['comunmente', 'comúnmente', 'comunménte', 'còmunmente'],
    correcta: 1,
    explicacion: 'Adverbios en -mente conservan la tilde del adjetivo base: común → comúnmente (RAE, §3.3.4).',
    dificultad: 3,
  },
  {
    categoria: 'acentuacion',
    enunciado: 'Señale la acentuación CORRECTA del adverbio:',
    opciones: ['hábilmente', 'habilmente', 'habilménte', 'hàbilmente'],
    correcta: 0,
    explicacion: 'Adverbios en -mente conservan la tilde del adjetivo base: hábil → hábilmente (RAE, §3.3.4).',
    dificultad: 3,
  },
  {
    categoria: 'acentuacion',
    enunciado: 'Señale la acentuación CORRECTA:',
    opciones: ['solamente', 'sólamente', 'solaménte', 'sòlamente'],
    correcta: 0,
    explicacion: '«Solo» no lleva tilde (RAE, Ortografía 2010), por tanto «solamente» tampoco la lleva.',
    dificultad: 3,
  },
  {
    categoria: 'acentuacion',
    enunciado: '¿Cuál de las siguientes palabras está CORRECTAMENTE acentuada?',
    opciones: ['guión', 'guion', 'güion', 'guìon'],
    correcta: 1,
    explicacion: 'Desde la Ortografía de 2010, «guion» se considera monosílabo y no lleva tilde (RAE, §3.4.3).',
    dificultad: 3,
  },
  {
    categoria: 'acentuacion',
    enunciado: '¿Cuál de las siguientes palabras está CORRECTAMENTE acentuada?',
    opciones: ['truhán', 'truhan', 'trúhan', 'truàn'],
    correcta: 0,
    explicacion: '«Truhán» es bisílaba aguda terminada en -n: lleva tilde (RAE, §3.3).',
    dificultad: 3,
  },
  {
    categoria: 'acentuacion',
    enunciado: 'Señale la opción CORRECTA:',
    opciones: [
      'Solo quiero un café',
      'Sólo quiero un café',
      'Solò quiero un café',
      'Sôlo quiero un café',
    ],
    correcta: 0,
    explicacion: 'La RAE (Ortografía 2010) prescribe no tildar «solo» ni siquiera cuando es adverbio.',
    dificultad: 3,
  },
  {
    categoria: 'acentuacion',
    enunciado: 'Señale la opción CORRECTA:',
    opciones: [
      'Éste es mi libro',
      'Este es mi libro',
      'Esté es mi libro',
      'Èste es mi libro',
    ],
    correcta: 1,
    explicacion: 'Los demostrativos (este, ese, aquel) no llevan tilde en ningún caso según la RAE (Ortografía 2010, §3.4.3).',
    dificultad: 3,
  },
  {
    categoria: 'acentuacion',
    enunciado: 'Señale la palabra CORRECTAMENTE acentuada:',
    opciones: ['compas', 'compás', 'cómpas', 'compàs'],
    correcta: 1,
    explicacion: 'Aguda terminada en -s: lleva tilde (RAE, §3.3).',
    dificultad: 1,
  },
  {
    categoria: 'acentuacion',
    enunciado: '¿Cuál de las siguientes oraciones usa CORRECTAMENTE la tilde diacrítica?',
    opciones: [
      'Aun no ha llegado',
      'Aún no ha llegado',
      'Àun no ha llegado',
      'Aùn no ha llegado',
    ],
    correcta: 1,
    explicacion: '«Aún» (= todavía) lleva tilde. «Aun» (= incluso) no la lleva (RAE, §3.4.1).',
    dificultad: 2,
  },
]

// ─── B / V (~25 ítems) ──────────────────────────────────────────────────────

const B_V: OrtografiaItem[] = [
  // Dificultad 1
  {
    categoria: 'b_v',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['absorver', 'absorber', 'abzorber', 'abzorver'],
    correcta: 1,
    explicacion: 'Se escribe con b: «absorber». Después de «b» nunca va «v» en la misma sílaba (RAE).',
    dificultad: 1,
  },
  {
    categoria: 'b_v',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['obvio', 'ovvio', 'obvió', 'ovio'],
    correcta: 0,
    explicacion: 'Se escribe «obvio» con b: grupo consonántico «bv» (RAE).',
    dificultad: 1,
  },
  {
    categoria: 'b_v',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['emvolver', 'envolver', 'enbolver', 'embolver'],
    correcta: 1,
    explicacion: 'Antes de v siempre se escribe n (nunca m): «envolver» (RAE).',
    dificultad: 1,
  },
  {
    categoria: 'b_v',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['tamvién', 'tanbien', 'también', 'tanvién'],
    correcta: 2,
    explicacion: 'Antes de b y p se escribe m (nunca n): «también» (RAE).',
    dificultad: 1,
  },
  {
    categoria: 'b_v',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['combinar', 'convinar', 'conbinar', 'comvinar'],
    correcta: 0,
    explicacion: 'Antes de b se escribe m: «combinar». Además, se escribe con b (del latín combinare).',
    dificultad: 1,
  },
  {
    categoria: 'b_v',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['emvidia', 'envidia', 'enmbidia', 'embidia'],
    correcta: 1,
    explicacion: 'Antes de v se escribe n: «envidia» (RAE).',
    dificultad: 1,
  },
  {
    categoria: 'b_v',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['invención', 'imbención', 'inbención', 'imvención'],
    correcta: 0,
    explicacion: 'Antes de v se escribe n: «invención» (RAE).',
    dificultad: 1,
  },
  {
    categoria: 'b_v',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['ambulancia', 'amvulancia', 'anbulancia', 'anvulancia'],
    correcta: 0,
    explicacion: 'Antes de b se escribe m: «ambulancia» (RAE).',
    dificultad: 1,
  },
  // Dificultad 2
  {
    categoria: 'b_v',
    enunciado: 'Complete: «Ayer ______ mucho calor en la ciudad.»',
    opciones: ['tubo', 'tuvo', 'túvo', 'túbo'],
    correcta: 1,
    explicacion: '«Tuvo» es pretérito del verbo tener (con v). «Tubo» es un sustantivo (cilindro hueco).',
    dificultad: 2,
  },
  {
    categoria: 'b_v',
    enunciado: 'Complete: «El agua empezó a ______.»',
    opciones: ['herbir', 'hervir', 'herbír', 'hervír'],
    correcta: 1,
    explicacion: '«Hervir» se escribe con v. Es un error frecuente escribirlo con b.',
    dificultad: 2,
  },
  {
    categoria: 'b_v',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['recivir', 'resibir', 'recibir', 'resivir'],
    correcta: 2,
    explicacion: '«Recibir» se escribe con c y b (del latín recipĕre).',
    dificultad: 2,
  },
  {
    categoria: 'b_v',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['escrivir', 'escribir', 'escriuir', 'ezcribir'],
    correcta: 1,
    explicacion: '«Escribir» se escribe con b (del latín scribĕre).',
    dificultad: 2,
  },
  {
    categoria: 'b_v',
    enunciado: 'Complete: «Es ______ que llueva mañana.»',
    opciones: ['probale', 'provable', 'probable', 'provavle'],
    correcta: 2,
    explicacion: '«Probable» se escribe con b: terminación -ble (RAE).',
    dificultad: 2,
  },
  {
    categoria: 'b_v',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['atrivuir', 'atribuir', 'atrivuír', 'atribuír'],
    correcta: 1,
    explicacion: '«Atribuir» se escribe con b (del latín attribuĕre).',
    dificultad: 2,
  },
  {
    categoria: 'b_v',
    enunciado: 'Complete: «El detective ______ la escena del crimen.»',
    opciones: ['obserbo', 'observo', 'observó', 'obserbó'],
    correcta: 2,
    explicacion: '«Observó» (pretérito) se escribe con -bs- y v (del latín observāre).',
    dificultad: 2,
  },
  // Dificultad 3
  {
    categoria: 'b_v',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['probeer', 'proveer', 'provher', 'probher'],
    correcta: 1,
    explicacion: '«Proveer» se escribe con v (del latín providēre). No confundir con «probar».',
    dificultad: 3,
  },
  {
    categoria: 'b_v',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['subvención', 'subención', 'suvvención', 'suvención'],
    correcta: 0,
    explicacion: '«Subvención» mantiene el prefijo sub- + v (RAE).',
    dificultad: 3,
  },
  {
    categoria: 'b_v',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['bienbenida', 'vienvenida', 'bienvenida', 'vienbenida'],
    correcta: 2,
    explicacion: '«Bienvenida»: «bien» con b + «venida» con v (del verbo venir).',
    dificultad: 3,
  },
  {
    categoria: 'b_v',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['adverbio', 'adverbío', 'adberbio', 'adverbìo'],
    correcta: 0,
    explicacion: '«Adverbio»: prefijo ad- + verbio (del latín adverbium). Se escribe con dv.',
    dificultad: 3,
  },
  {
    categoria: 'b_v',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['bivir', 'vibir', 'bivír', 'vivir'],
    correcta: 3,
    explicacion: '«Vivir» se escribe con v en ambas sílabas (del latín vivĕre).',
    dificultad: 3,
  },
  {
    categoria: 'b_v',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['herbívoro', 'hervíboro', 'herbíboro', 'hervívoro'],
    correcta: 0,
    explicacion: '«Herbívoro»: hierba (herb-) con b + -voro (del latín vorāre, devorar) con v.',
    dificultad: 3,
  },
  {
    categoria: 'b_v',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['contríbuir', 'contribuir', 'contrihuir', 'contrivuir'],
    correcta: 1,
    explicacion: '«Contribuir» se escribe con b (del latín contribuĕre).',
    dificultad: 3,
  },
  {
    categoria: 'b_v',
    enunciado: 'Complete: «La vacuna fue un gran ______ médico.»',
    opciones: ['havance', 'abance', 'avance', 'habance'],
    correcta: 2,
    explicacion: '«Avance» se escribe con v (del verbo avanzar, con v).',
    dificultad: 3,
  },
  {
    categoria: 'b_v',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['devolber', 'debolber', 'debolver', 'devolver'],
    correcta: 3,
    explicacion: '«Devolver» se escribe con v en ambos casos: de- + volver (RAE).',
    dificultad: 3,
  },
  {
    categoria: 'b_v',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['resolber', 'rezolver', 'resolver', 'resolbér'],
    correcta: 2,
    explicacion: '«Resolver» se escribe con v (del latín resolvĕre).',
    dificultad: 2,
  },
]

// ─── H (~25 ítems) ──────────────────────────────────────────────────────────

const H_ITEMS: OrtografiaItem[] = [
  // Dificultad 1
  {
    categoria: 'h',
    enunciado: 'Señale la opción CORRECTA:',
    opciones: ['aver', 'haber', 'haver', 'aber'],
    correcta: 1,
    explicacion: '«Haber» se escribe con h y b (del latín habēre).',
    dificultad: 1,
  },
  {
    categoria: 'h',
    enunciado: 'Señale la opción CORRECTA:',
    opciones: ['acer', 'aser', 'hacer', 'haser'],
    correcta: 2,
    explicacion: '«Hacer» se escribe con h y c (del latín facĕre).',
    dificultad: 1,
  },
  {
    categoria: 'h',
    enunciado: 'Señale la opción CORRECTA:',
    opciones: ['ablar', 'hablar', 'havlar', 'hablár'],
    correcta: 1,
    explicacion: '«Hablar» se escribe con h (del latín fabulāre).',
    dificultad: 1,
  },
  {
    categoria: 'h',
    enunciado: 'Señale la opción CORRECTA:',
    opciones: ['ijo', 'hijo', 'hixo', 'ixo'],
    correcta: 1,
    explicacion: '«Hijo» se escribe con h (del latín filium). Las palabras que empiezan por hie-, hue- llevan h.',
    dificultad: 1,
  },
  {
    categoria: 'h',
    enunciado: 'Señale la opción CORRECTA:',
    opciones: ['ueso', 'gueso', 'hueso', 'weso'],
    correcta: 2,
    explicacion: '«Hueso» se escribe con h: las palabras que empiezan por hue- llevan h (RAE).',
    dificultad: 1,
  },
  {
    categoria: 'h',
    enunciado: 'Señale la opción CORRECTA:',
    opciones: ['uevo', 'güevo', 'huevo', 'wevo'],
    correcta: 2,
    explicacion: '«Huevo» se escribe con h: las palabras que empiezan por hue- llevan h (RAE).',
    dificultad: 1,
  },
  {
    categoria: 'h',
    enunciado: 'Señale la opción CORRECTA:',
    opciones: ['ierro', 'hierro', 'yerro', 'hiyerro'],
    correcta: 1,
    explicacion: '«Hierro» (metal) se escribe con h. «Yerro» (error) es otra palabra.',
    dificultad: 1,
  },
  {
    categoria: 'h',
    enunciado: 'Señale la opción CORRECTA:',
    opciones: ['abitación', 'havitación', 'habitación', 'avitación'],
    correcta: 2,
    explicacion: '«Habitación» se escribe con h y b (del latín habitatio).',
    dificultad: 1,
  },
  // Dificultad 2
  {
    categoria: 'h',
    enunciado: 'Complete: «Vamos ______ qué pasa.»',
    opciones: ['haber', 'a ver', 'haver', 'a ber'],
    correcta: 1,
    explicacion: '«A ver» (preposición + infinitivo) se usa para «mirar/comprobar». «Haber» es verbo auxiliar o impersonal.',
    dificultad: 2,
  },
  {
    categoria: 'h',
    enunciado: 'Complete: «Lo ha ______ él mismo.»',
    opciones: ['echo', 'hecho', 'hechó', 'echó'],
    correcta: 1,
    explicacion: '«Hecho» es participio de hacer. «Echo» es del verbo echar.',
    dificultad: 2,
  },
  {
    categoria: 'h',
    enunciado: 'Complete: «La ropa está ______ a perder.»',
    opciones: ['hecha', 'echa', 'ehca', 'hehca'],
    correcta: 0,
    explicacion: '«Hecha» (participio de hacer): «estar hecha a perder» = estar arruinada.',
    dificultad: 2,
  },
  {
    categoria: 'h',
    enunciado: 'Complete: «______ la carta al buzón.»',
    opciones: ['Hecha', 'Echa', 'Ehca', 'Heca'],
    correcta: 1,
    explicacion: '«Echa» del verbo echar (lanzar, depositar). No confundir con «hecha» (participio de hacer).',
    dificultad: 2,
  },
  {
    categoria: 'h',
    enunciado: 'Complete: «Se ha ______ del viejo sofá.»',
    opciones: ['desecho', 'deshecho', 'dezecho', 'dezhecho'],
    correcta: 1,
    explicacion: '«Deshecho» es participio de deshacer. «Desecho» es sustantivo (residuo, desperdicio).',
    dificultad: 2,
  },
  {
    categoria: 'h',
    enunciado: 'Señale la opción CORRECTA:',
    opciones: ['almohada', 'almoada', 'almoháda', 'halmoada'],
    correcta: 0,
    explicacion: '«Almohada» se escribe con h intercalada (del árabe al-mujadda).',
    dificultad: 2,
  },
  {
    categoria: 'h',
    enunciado: 'Señale la opción CORRECTA:',
    opciones: ['aora', 'ahora', 'haora', 'haorà'],
    correcta: 1,
    explicacion: '«Ahora» se escribe con h intercalada (del latín hac hōrā).',
    dificultad: 2,
  },
  {
    categoria: 'h',
    enunciado: 'Señale la opción CORRECTA:',
    opciones: ['prohibir', 'proibir', 'prohivir', 'proívir'],
    correcta: 0,
    explicacion: '«Prohibir» se escribe con h intercalada y b (del latín prohibēre).',
    dificultad: 2,
  },
  // Dificultad 3
  {
    categoria: 'h',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['exausto', 'exhausto', 'exháusto', 'ehxausto'],
    correcta: 1,
    explicacion: '«Exhausto» se escribe con h después de ex- (del latín exhaustus).',
    dificultad: 3,
  },
  {
    categoria: 'h',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['inhibir', 'inibir', 'hinibir', 'innibir'],
    correcta: 0,
    explicacion: '«Inhibir» se escribe con h intercalada (del latín inhibēre).',
    dificultad: 3,
  },
  {
    categoria: 'h',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['esortar', 'exhortar', 'exortar', 'ehsortar'],
    correcta: 1,
    explicacion: '«Exhortar» se escribe con h intercalada (del latín exhortāri).',
    dificultad: 3,
  },
  {
    categoria: 'h',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['vehículo', 'veículo', 'behículo', 'vehiculo'],
    correcta: 0,
    explicacion: '«Vehículo» se escribe con h intercalada y tilde en la í (esdrújula, del latín vehicŭlum).',
    dificultad: 3,
  },
  {
    categoria: 'h',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['coherente', 'coerente', 'cojerente', 'coheherente'],
    correcta: 0,
    explicacion: '«Coherente» se escribe con h intercalada (del latín cohaerentem).',
    dificultad: 3,
  },
  {
    categoria: 'h',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['adherirse', 'aderirse', 'adherírse', 'haderirse'],
    correcta: 0,
    explicacion: '«Adherirse» se escribe con h intercalada (del latín adhaerēre).',
    dificultad: 3,
  },
  {
    categoria: 'h',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['aprehender', 'aprender', 'apreender', 'haprehender'],
    correcta: 0,
    explicacion: '«Aprehender» (capturar, asimilar) lleva h intercalada. Distinto de «aprender» (estudiar).',
    dificultad: 3,
  },
  {
    categoria: 'h',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['desahuciar', 'desauciar', 'desahusiar', 'dezauciar'],
    correcta: 0,
    explicacion: '«Desahuciar» se escribe con h intercalada (des- + ahuciar).',
    dificultad: 3,
  },
]

// ─── G / J (~25 ítems) ──────────────────────────────────────────────────────

const G_J: OrtografiaItem[] = [
  // Dificultad 1
  {
    categoria: 'g_j',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['protejer', 'proteger', 'protejér', 'protegér'],
    correcta: 1,
    explicacion: 'Los verbos terminados en -ger se escriben con g: «proteger» (excepto tejer y crujir).',
    dificultad: 1,
  },
  {
    categoria: 'g_j',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['cojer', 'coger', 'cojér', 'cogér'],
    correcta: 1,
    explicacion: 'Los verbos terminados en -ger se escriben con g: «coger» (RAE).',
    dificultad: 1,
  },
  {
    categoria: 'g_j',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['dirijir', 'dirigir', 'dirijír', 'dirigír'],
    correcta: 1,
    explicacion: 'Los verbos terminados en -gir se escriben con g: «dirigir» (RAE).',
    dificultad: 1,
  },
  {
    categoria: 'g_j',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['elejir', 'elegir', 'elejír', 'eligír'],
    correcta: 1,
    explicacion: 'Los verbos terminados en -gir se escriben con g: «elegir» (RAE).',
    dificultad: 1,
  },
  {
    categoria: 'g_j',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['recojemos', 'recogemos', 'recojémos', 'recogémos'],
    correcta: 1,
    explicacion: '«Recoger» mantiene la g ante -e: «recogemos» (RAE).',
    dificultad: 1,
  },
  {
    categoria: 'g_j',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['ajente', 'agente', 'ajénte', 'agénte'],
    correcta: 1,
    explicacion: '«Agente» se escribe con g (del latín agentem). Las palabras con gen- se escriben con g (RAE).',
    dificultad: 1,
  },
  {
    categoria: 'g_j',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['jénero', 'género', 'jenero', 'genero'],
    correcta: 1,
    explicacion: '«Género» se escribe con g y tilde (esdrújula). Las palabras con gen- se escriben con g.',
    dificultad: 1,
  },
  {
    categoria: 'g_j',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['imágen', 'imagen', 'imájen', 'imajen'],
    correcta: 1,
    explicacion: '«Imagen» se escribe con g. Es llana terminada en -n, por eso NO lleva tilde.',
    dificultad: 1,
  },
  // Dificultad 2
  {
    categoria: 'g_j',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['ingerencia', 'injerencia', 'ingerensia', 'injerensia'],
    correcta: 1,
    explicacion: '«Injerencia» (intromisión) se escribe con j. Es excepción a la regla de gen- con g.',
    dificultad: 2,
  },
  {
    categoria: 'g_j',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['crugir', 'crujir', 'crugír', 'crujír'],
    correcta: 1,
    explicacion: '«Crujir» se escribe con j. Es excepción a la regla de los verbos en -gir.',
    dificultad: 2,
  },
  {
    categoria: 'g_j',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['teger', 'tejer', 'tegér', 'tejér'],
    correcta: 1,
    explicacion: '«Tejer» se escribe con j. Es excepción a la regla de los verbos en -ger.',
    dificultad: 2,
  },
  {
    categoria: 'g_j',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['equipage', 'equipaje', 'equipague', 'ekipaje'],
    correcta: 1,
    explicacion: 'Las palabras terminadas en -aje se escriben con j: «equipaje» (RAE).',
    dificultad: 2,
  },
  {
    categoria: 'g_j',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['mensage', 'mensaje', 'mensague', 'mensagge'],
    correcta: 1,
    explicacion: 'Las palabras terminadas en -aje se escriben con j: «mensaje» (RAE).',
    dificultad: 2,
  },
  {
    categoria: 'g_j',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['conduge', 'conduje', 'condugé', 'condujé'],
    correcta: 1,
    explicacion: 'El pretérito de «conducir» se escribe con j: «conduje» (RAE).',
    dificultad: 2,
  },
  {
    categoria: 'g_j',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['trage', 'traje', 'tragé', 'trajé'],
    correcta: 1,
    explicacion: 'El pretérito de «traer» se escribe con j: «traje». También el sustantivo «traje» (vestimenta).',
    dificultad: 2,
  },
  {
    categoria: 'g_j',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['dige', 'dije', 'digé', 'dijé'],
    correcta: 1,
    explicacion: 'El pretérito de «decir» se escribe con j: «dije» (RAE).',
    dificultad: 2,
  },
  // Dificultad 3
  {
    categoria: 'g_j',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['hegemonía', 'hejemonía', 'hegemonìa', 'hejemonìa'],
    correcta: 0,
    explicacion: '«Hegemonía» se escribe con g (del griego hēgemonía).',
    dificultad: 3,
  },
  {
    categoria: 'g_j',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['cónyuje', 'cónyuge', 'conjuje', 'conjuge'],
    correcta: 1,
    explicacion: '«Cónyuge» se escribe con g final (del latín coniugem). Esdrújula.',
    dificultad: 3,
  },
  {
    categoria: 'g_j',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['jénesis', 'génesis', 'genésis', 'jenésis'],
    correcta: 1,
    explicacion: '«Génesis» se escribe con g (del griego génesis). Esdrújula.',
    dificultad: 3,
  },
  {
    categoria: 'g_j',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['legítimo', 'lejítimo', 'legitimo', 'lejitimo'],
    correcta: 0,
    explicacion: '«Legítimo» se escribe con g (del latín legitĭmus). Esdrújula.',
    dificultad: 3,
  },
  {
    categoria: 'g_j',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['flagrante', 'flajrante', 'fraglante', 'frajlante'],
    correcta: 0,
    explicacion: '«Flagrante» se escribe con g (del latín flagrantem).',
    dificultad: 3,
  },
  {
    categoria: 'g_j',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['jestión', 'gestión', 'jestion', 'gestion'],
    correcta: 1,
    explicacion: '«Gestión» se escribe con g y tilde (aguda terminada en -n, del latín gestionem).',
    dificultad: 3,
  },
  {
    categoria: 'g_j',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['verígene', 'verígine', 'vertigine', 'vértigo'],
    correcta: 3,
    explicacion: '«Vértigo» se escribe con g (del latín vertīgo). Esdrújula.',
    dificultad: 3,
  },
  {
    categoria: 'g_j',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['exijir', 'exigir', 'exijír', 'exigír'],
    correcta: 1,
    explicacion: '«Exigir» se escribe con g: verbo terminado en -gir (RAE).',
    dificultad: 1,
  },
  {
    categoria: 'g_j',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['garaje', 'garage', 'garague', 'garáge'],
    correcta: 0,
    explicacion: '«Garaje» se escribe con j: palabras terminadas en -aje llevan j (RAE).',
    dificultad: 2,
  },
]

// ─── LL / Y (~20 ítems) ─────────────────────────────────────────────────────

const LL_Y: OrtografiaItem[] = [
  // Dificultad 1
  {
    categoria: 'll_y',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['caye', 'calle', 'callé', 'cayé'],
    correcta: 1,
    explicacion: '«Calle» se escribe con ll (del latín callem).',
    dificultad: 1,
  },
  {
    categoria: 'll_y',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['llegar', 'yegar', 'yegár', 'llegár'],
    correcta: 0,
    explicacion: '«Llegar» se escribe con ll (del latín plicāre).',
    dificultad: 1,
  },
  {
    categoria: 'll_y',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['lluvia', 'yuvia', 'llubía', 'yubía'],
    correcta: 0,
    explicacion: '«Lluvia» se escribe con ll y v (del latín pluvĭa).',
    dificultad: 1,
  },
  {
    categoria: 'll_y',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['batayla', 'vatalla', 'batalla', 'batailla'],
    correcta: 2,
    explicacion: '«Batalla» se escribe con ll (del francés bataille).',
    dificultad: 1,
  },
  {
    categoria: 'll_y',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['llaves', 'yaves', 'llabes', 'yáves'],
    correcta: 0,
    explicacion: '«Llaves» se escribe con ll (del latín clavem).',
    dificultad: 1,
  },
  {
    categoria: 'll_y',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['proyecto', 'proiecto', 'proyectó', 'prollecto'],
    correcta: 0,
    explicacion: '«Proyecto» se escribe con y (del latín proiectus). Llana terminada en vocal: no lleva tilde.',
    dificultad: 1,
  },
  {
    categoria: 'll_y',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['aller', 'ayer', 'ayèr', 'ayér'],
    correcta: 1,
    explicacion: '«Ayer» se escribe con y (del latín ad hĕri).',
    dificultad: 1,
  },
  // Dificultad 2
  {
    categoria: 'll_y',
    enunciado: 'Complete: «El queso estaba ______ por los bordes.»',
    opciones: ['rayado', 'rallado', 'rayádo', 'ralládo'],
    correcta: 1,
    explicacion: '«Rallado» (de rallar, desmenuzar con rallador) con ll. «Rayado» (con rayas) con y.',
    dificultad: 2,
  },
  {
    categoria: 'll_y',
    enunciado: 'Complete: «Necesito una ______ para pasar.»',
    opciones: ['vaya', 'valla', 'baya', 'balla'],
    correcta: 1,
    explicacion: '«Valla» (cercado) con ll. «Vaya» (verbo ir) con y. «Baya» (fruto) con y.',
    dificultad: 2,
  },
  {
    categoria: 'll_y',
    enunciado: 'Complete: «El ______ pasaba junto a la finca.»',
    opciones: ['arrollo', 'arroyo', 'harroyo', 'harrollo'],
    correcta: 1,
    explicacion: '«Arroyo» (corriente de agua) con y. «Arrollo» (de arrollar, atropellar) con ll.',
    dificultad: 2,
  },
  {
    categoria: 'll_y',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['inyectar', 'inllectar', 'inyectár', 'inllectár'],
    correcta: 0,
    explicacion: '«Inyectar» se escribe con y (del latín iniectāre).',
    dificultad: 2,
  },
  {
    categoria: 'll_y',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['bullicio', 'buyicio', 'bullisio', 'buyisio'],
    correcta: 0,
    explicacion: '«Bullicio» se escribe con ll (del latín bullītium).',
    dificultad: 2,
  },
  {
    categoria: 'll_y',
    enunciado: 'Complete: «El barco echó la ______ para no hundirse.»',
    opciones: ['quiya', 'quilla', 'killa', 'kiya'],
    correcta: 1,
    explicacion: '«Quilla» (parte inferior del barco) se escribe con ll.',
    dificultad: 2,
  },
  // Dificultad 3
  {
    categoria: 'll_y',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['bolla', 'boya', 'boia', 'volla'],
    correcta: 1,
    explicacion: '«Boya» (señal flotante) se escribe con y. «Bolla» no existe como palabra estándar.',
    dificultad: 3,
  },
  {
    categoria: 'll_y',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['yacimiento', 'llacimiento', 'llasimiento', 'yasimiento'],
    correcta: 0,
    explicacion: '«Yacimiento» se escribe con y (del verbo yacer, del latín iacēre).',
    dificultad: 3,
  },
  {
    categoria: 'll_y',
    enunciado: 'Complete: «El técnico detectó una ______ en el sistema.»',
    opciones: ['faya', 'falla', 'faia', 'fallá'],
    correcta: 1,
    explicacion: '«Falla» (defecto, avería) se escribe con ll.',
    dificultad: 3,
  },
  {
    categoria: 'll_y',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['destello', 'desteyo', 'destelló', 'desteyó'],
    correcta: 0,
    explicacion: '«Destello» se escribe con ll (de destellar).',
    dificultad: 3,
  },
  {
    categoria: 'll_y',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['joya', 'jolla', 'joia', 'jollá'],
    correcta: 0,
    explicacion: '«Joya» se escribe con y (del francés antiguo joie).',
    dificultad: 3,
  },
  {
    categoria: 'll_y',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['apoyar', 'apollar', 'apoiár', 'apollár'],
    correcta: 0,
    explicacion: '«Apoyar» se escribe con y (de apoyo, con y).',
    dificultad: 3,
  },
  {
    categoria: 'll_y',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['ensallo', 'ensayo', 'ensaio', 'enzayo'],
    correcta: 1,
    explicacion: '«Ensayo» se escribe con y (del latín exagium).',
    dificultad: 3,
  },
]

// ─── C / Z / S (~22 ítems) ──────────────────────────────────────────────────

const C_Z_S: OrtografiaItem[] = [
  // Dificultad 1
  {
    categoria: 'c_z_s',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['conoser', 'conozer', 'conocer', 'conoçer'],
    correcta: 2,
    explicacion: '«Conocer» se escribe con c ante e/i (del latín cognoscĕre).',
    dificultad: 1,
  },
  {
    categoria: 'c_z_s',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['desición', 'decisión', 'decición', 'desisión'],
    correcta: 1,
    explicacion: '«Decisión» se escribe con c-s (del latín decisionem).',
    dificultad: 1,
  },
  {
    categoria: 'c_z_s',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['nasión', 'nación', 'nazión', 'nassión'],
    correcta: 1,
    explicacion: '«Nación» se escribe con c (sufijo -ción). Las palabras con sufijo -ción se escriben con c.',
    dificultad: 1,
  },
  {
    categoria: 'c_z_s',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['felisidad', 'felicidad', 'felizidad', 'felissidad'],
    correcta: 1,
    explicacion: '«Felicidad» se escribe con c (del latín felicitatem).',
    dificultad: 1,
  },
  {
    categoria: 'c_z_s',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['piscina', 'pizcina', 'pissina', 'piçina'],
    correcta: 0,
    explicacion: '«Piscina» se escribe con sc (del latín piscīna).',
    dificultad: 1,
  },
  {
    categoria: 'c_z_s',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['hazer', 'haser', 'hacer', 'hacér'],
    correcta: 2,
    explicacion: '«Hacer» se escribe con c ante e/i (del latín facĕre).',
    dificultad: 1,
  },
  {
    categoria: 'c_z_s',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['esperansa', 'esperanza', 'ezperanza', 'hezperanza'],
    correcta: 1,
    explicacion: '«Esperanza» se escribe con z ante a (del latín sperantĭa).',
    dificultad: 1,
  },
  // Dificultad 2
  {
    categoria: 'c_z_s',
    enunciado: 'Complete: «La costurera sabe ______ muy bien.»',
    opciones: ['cozer', 'cocer', 'coser', 'cozér'],
    correcta: 2,
    explicacion: '«Coser» (unir con hilo) con s. «Cocer» (cocinar) con c. Aquí se habla de costura.',
    dificultad: 2,
  },
  {
    categoria: 'c_z_s',
    enunciado: 'Complete: «La ______ del tesoro fue emocionante.»',
    opciones: ['caza', 'casa', 'cassa', 'cazza'],
    correcta: 0,
    explicacion: '«Caza» (acción de cazar) con z. «Casa» (vivienda) con s.',
    dificultad: 2,
  },
  {
    categoria: 'c_z_s',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['adolecencia', 'adolescencia', 'adolecensia', 'adolesencia'],
    correcta: 1,
    explicacion: '«Adolescencia» se escribe con sc (del latín adolescentia).',
    dificultad: 2,
  },
  {
    categoria: 'c_z_s',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['conciensia', 'consiencia', 'conciencia', 'consciência'],
    correcta: 2,
    explicacion: '«Conciencia» se escribe con c-c (del latín conscientia). También es válido «consciencia».',
    dificultad: 2,
  },
  {
    categoria: 'c_z_s',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['sensillo', 'cencillo', 'sencillo', 'sencíllo'],
    correcta: 2,
    explicacion: '«Sencillo» se escribe con s y c (del latín singellum).',
    dificultad: 2,
  },
  {
    categoria: 'c_z_s',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['escaces', 'escacez', 'escasez', 'escasés'],
    correcta: 2,
    explicacion: '«Escasez» se escribe con s y z final (del adjetivo «escaso» + sufijo -ez).',
    dificultad: 2,
  },
  // Dificultad 3
  {
    categoria: 'c_z_s',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['ácido', 'ásido', 'ázido', 'hácido'],
    correcta: 0,
    explicacion: '«Ácido» se escribe con c (del latín acĭdum). Esdrújula.',
    dificultad: 3,
  },
  {
    categoria: 'c_z_s',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['exceso', 'ecseso', 'exeso', 'excéso'],
    correcta: 0,
    explicacion: '«Exceso» se escribe con xc (del latín excessus).',
    dificultad: 3,
  },
  {
    categoria: 'c_z_s',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['ascensor', 'acsensor', 'assensor', 'azcensor'],
    correcta: 0,
    explicacion: '«Ascensor» se escribe con sc (del latín ascensōrem).',
    dificultad: 3,
  },
  {
    categoria: 'c_z_s',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['resurección', 'resurrección', 'resureccion', 'resurrezción'],
    correcta: 1,
    explicacion: '«Resurrección» se escribe con doble r y cc (del latín resurrectionem).',
    dificultad: 3,
  },
  {
    categoria: 'c_z_s',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['eficasia', 'eficacia', 'eficásia', 'eficazia'],
    correcta: 1,
    explicacion: '«Eficacia» se escribe con c-c (del latín efficacia).',
    dificultad: 3,
  },
  {
    categoria: 'c_z_s',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['licensia', 'lizencia', 'licencia', 'lisencia'],
    correcta: 2,
    explicacion: '«Licencia» se escribe con c-c (del latín licentia).',
    dificultad: 3,
  },
  {
    categoria: 'c_z_s',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['perseveransia', 'perceverancia', 'perseverancia', 'perseveranzia'],
    correcta: 2,
    explicacion: '«Perseverancia» se escribe con s y c (del latín perseverantia).',
    dificultad: 3,
  },
  {
    categoria: 'c_z_s',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['disiplina', 'disziplina', 'disciplina', 'diciplina'],
    correcta: 2,
    explicacion: '«Disciplina» se escribe con sc (del latín disciplīna).',
    dificultad: 3,
  },
  {
    categoria: 'c_z_s',
    enunciado: 'Señale la palabra CORRECTAMENTE escrita:',
    opciones: ['organizasión', 'organización', 'organizazión', 'organisación'],
    correcta: 1,
    explicacion: '«Organización» se escribe con z y c (sufijo -ción). Del latín organizationem.',
    dificultad: 1,
  },
]

// ─── MAYÚSCULAS (~22 ítems) ─────────────────────────────────────────────────

const MAYUSCULAS: OrtografiaItem[] = [
  // Dificultad 1
  {
    categoria: 'mayusculas',
    enunciado: '¿Cuál de las siguientes frases usa CORRECTAMENTE las mayúsculas?',
    opciones: [
      'madrid es la Capital de españa.',
      'Madrid es la capital de España.',
      'madrid es la capital de españa.',
      'Madrid Es La Capital De España.',
    ],
    correcta: 1,
    explicacion: 'Los nombres propios de ciudad y país llevan mayúscula. «Capital» no es nombre propio (RAE, §4.2).',
    dificultad: 1,
  },
  {
    categoria: 'mayusculas',
    enunciado: '¿Cuál de las siguientes frases usa CORRECTAMENTE las mayúsculas?',
    opciones: [
      'Mi amigo juan vive en bilbao.',
      'Mi amigo Juan vive en Bilbao.',
      'Mi Amigo Juan Vive En Bilbao.',
      'Mi amigo juan vive en Bilbao.',
    ],
    correcta: 1,
    explicacion: 'Los nombres propios de persona y ciudad van en mayúscula (RAE, §4.2).',
    dificultad: 1,
  },
  {
    categoria: 'mayusculas',
    enunciado: '¿Cuál de las siguientes frases usa CORRECTAMENTE las mayúsculas?',
    opciones: [
      'El río Ebro desemboca en el mar Mediterráneo.',
      'El Río Ebro desemboca en el Mar Mediterráneo.',
      'el río Ebro desemboca en el mar Mediterráneo.',
      'El río ebro desemboca en el mar mediterráneo.',
    ],
    correcta: 0,
    explicacion: '«Ebro» y «Mediterráneo» son nombres propios. «Río» y «mar» son nombres genéricos y van en minúscula (RAE, §4.2).',
    dificultad: 1,
  },
  {
    categoria: 'mayusculas',
    enunciado: '¿Cuál de las siguientes frases usa CORRECTAMENTE las mayúsculas?',
    opciones: [
      'La Organización de las naciones unidas se fundó en 1945.',
      'La Organización de las Naciones Unidas se fundó en 1945.',
      'La organización de las naciones unidas se fundó en 1945.',
      'La organización de las Naciones Unidas se fundó en 1945.',
    ],
    correcta: 1,
    explicacion: 'Los nombres oficiales de organizaciones e instituciones van en mayúscula (RAE, §4.4).',
    dificultad: 1,
  },
  {
    categoria: 'mayusculas',
    enunciado: '¿Cuál de las siguientes frases usa CORRECTAMENTE las mayúsculas?',
    opciones: [
      'Fuimos al museo del Prado el Lunes.',
      'Fuimos al Museo del Prado el lunes.',
      'Fuimos al museo del prado el lunes.',
      'fuimos al Museo del Prado el lunes.',
    ],
    correcta: 1,
    explicacion: '«Museo del Prado» es nombre propio de institución. Los días de la semana van en minúscula (RAE, §4.6).',
    dificultad: 1,
  },
  {
    categoria: 'mayusculas',
    enunciado: '¿Cuál de las siguientes frases usa CORRECTAMENTE las mayúsculas?',
    opciones: [
      'En Enero hace mucho frío.',
      'En enero hace mucho frío.',
      'en Enero hace mucho Frío.',
      'en enero hace mucho frío.',
    ],
    correcta: 1,
    explicacion: 'Los meses del año se escriben en minúscula en español (RAE, §4.6).',
    dificultad: 1,
  },
  {
    categoria: 'mayusculas',
    enunciado: '¿Cuál de las siguientes frases usa CORRECTAMENTE las mayúsculas?',
    opciones: [
      'La Constitución Española fue aprobada en 1978.',
      'La constitución española fue aprobada en 1978.',
      'La Constitución española fue aprobada en 1978.',
      'la Constitución Española fue aprobada en 1978.',
    ],
    correcta: 2,
    explicacion: '«Constitución» va en mayúscula como nombre oficial de documento; «española» es adjetivo y va en minúscula (RAE, §4.4).',
    dificultad: 1,
  },
  // Dificultad 2
  {
    categoria: 'mayusculas',
    enunciado: '¿Cuál de las siguientes frases usa CORRECTAMENTE las mayúsculas?',
    opciones: [
      'El Presidente del Gobierno llegó a las diez.',
      'El presidente del gobierno llegó a las diez.',
      'El presidente del Gobierno llegó a las diez.',
      'el Presidente del gobierno llegó a las Diez.',
    ],
    correcta: 2,
    explicacion: 'Los cargos (presidente) van en minúscula. «Gobierno» con mayúscula cuando se refiere al órgano concreto del Estado (RAE, §4.4).',
    dificultad: 2,
  },
  {
    categoria: 'mayusculas',
    enunciado: '¿Cuál de las siguientes frases usa CORRECTAMENTE las mayúsculas?',
    opciones: [
      'El Papa visitó la iglesia de San Pedro.',
      'El papa visitó la iglesia de San Pedro.',
      'El papa visitó la Iglesia de san Pedro.',
      'El Papa visitó la Iglesia de San Pedro.',
    ],
    correcta: 1,
    explicacion: 'Los cargos y títulos (papa, rey, presidente) van en minúscula. «San Pedro» es nombre propio (RAE, §4.3).',
    dificultad: 2,
  },
  {
    categoria: 'mayusculas',
    enunciado: '¿Cuál de las siguientes frases usa CORRECTAMENTE las mayúsculas?',
    opciones: [
      'El director General presidió la reunión.',
      'El Director General presidió la reunión.',
      'El director general presidió la reunión.',
      'el director general Presidió la reunión.',
    ],
    correcta: 2,
    explicacion: 'Los cargos y sus modificadores van en minúscula cuando son genéricos (RAE, §4.3).',
    dificultad: 2,
  },
  {
    categoria: 'mayusculas',
    enunciado: '¿Cuál de las siguientes frases usa CORRECTAMENTE las mayúsculas?',
    opciones: [
      'Los Derechos Humanos son universales.',
      'Los derechos humanos son universales.',
      'los Derechos Humanos son universales.',
      'los derechos humanos son Universales.',
    ],
    correcta: 1,
    explicacion: '«Derechos humanos» como concepto genérico va en minúscula. Solo lleva mayúscula en el título oficial del documento (RAE, §4.4).',
    dificultad: 2,
  },
  {
    categoria: 'mayusculas',
    enunciado: '¿Cuál de las siguientes frases usa CORRECTAMENTE las mayúsculas?',
    opciones: [
      'Estudia Medicina en la universidad de Salamanca.',
      'Estudia medicina en la Universidad de Salamanca.',
      'Estudia Medicina en la Universidad de Salamanca.',
      'estudia medicina en la universidad de Salamanca.',
    ],
    correcta: 1,
    explicacion: '«Medicina» como disciplina genérica va en minúscula. «Universidad de Salamanca» es nombre propio de institución (RAE, §4.4).',
    dificultad: 2,
  },
  {
    categoria: 'mayusculas',
    enunciado: '¿Cuál de las siguientes frases usa CORRECTAMENTE las mayúsculas?',
    opciones: [
      'El artículo 14 de la constitución española garantiza la igualdad.',
      'El artículo 14 de la Constitución española garantiza la igualdad.',
      'El Artículo 14 de la Constitución Española garantiza la igualdad.',
      'El artículo 14 de la Constitución Española garantiza la Igualdad.',
    ],
    correcta: 1,
    explicacion: '«Artículo» genérico en minúscula. «Constitución» con mayúscula (nombre oficial). «Española» adjetivo en minúscula (RAE, §4.4).',
    dificultad: 2,
  },
  // Dificultad 3
  {
    categoria: 'mayusculas',
    enunciado: '¿Cuál de las siguientes frases usa CORRECTAMENTE las mayúsculas?',
    opciones: [
      'Los Españoles celebran la Navidad.',
      'Los españoles celebran la Navidad.',
      'Los españoles celebran la navidad.',
      'Los Españoles celebran la navidad.',
    ],
    correcta: 1,
    explicacion: 'Los gentilicios (españoles) van en minúscula. «Navidad» como festividad va en mayúscula (RAE, §4.6).',
    dificultad: 3,
  },
  {
    categoria: 'mayusculas',
    enunciado: '¿Cuál de las siguientes frases usa CORRECTAMENTE las mayúsculas?',
    opciones: [
      'El norte de España es más lluvioso.',
      'El Norte de España es más lluvioso.',
      'el norte de españa es más lluvioso.',
      'El norte de españa es más lluvioso.',
    ],
    correcta: 0,
    explicacion: 'Los puntos cardinales van en minúscula cuando indican dirección o ubicación genérica. Solo van en mayúscula como nombres propios de zonas geopolíticas (RAE, §4.5).',
    dificultad: 3,
  },
  {
    categoria: 'mayusculas',
    enunciado: '¿Cuál de las siguientes frases usa CORRECTAMENTE las mayúsculas?',
    opciones: [
      'La ley orgánica 2/1986 regula las Fuerzas y Cuerpos de Seguridad.',
      'La Ley Orgánica 2/1986 regula las Fuerzas y Cuerpos de Seguridad.',
      'La ley orgánica 2/1986 regula las fuerzas y cuerpos de seguridad.',
      'La Ley orgánica 2/1986 regula las fuerzas y cuerpos de seguridad.',
    ],
    correcta: 1,
    explicacion: '«Ley Orgánica» con mayúscula cuando se cita con su número oficial. «Fuerzas y Cuerpos de Seguridad» es denominación oficial (RAE, §4.4).',
    dificultad: 3,
  },
  {
    categoria: 'mayusculas',
    enunciado: '¿Cuál de las siguientes frases usa CORRECTAMENTE las mayúsculas?',
    opciones: [
      'El Gobierno aprobó el real Decreto ayer.',
      'El gobierno aprobó el Real Decreto ayer.',
      'El Gobierno aprobó el real decreto ayer.',
      'El gobierno aprobó el real decreto ayer.',
    ],
    correcta: 2,
    explicacion: '«Gobierno» como órgano del Estado puede ir en mayúscula. «Real decreto» genérico (sin número) va en minúscula (RAE, §4.4). Se acepta «Gobierno» en mayúscula referido al órgano.',
    dificultad: 3,
  },
  {
    categoria: 'mayusculas',
    enunciado: '¿Cuál de las siguientes frases usa CORRECTAMENTE las mayúsculas?',
    opciones: [
      'Se licenció en Derecho por la universidad Complutense de madrid.',
      'Se licenció en derecho por la Universidad Complutense de Madrid.',
      'Se licenció en Derecho por la Universidad Complutense de Madrid.',
      'se licenció en derecho por la Universidad complutense de Madrid.',
    ],
    correcta: 1,
    explicacion: '«Derecho» como disciplina genérica va en minúscula. «Universidad Complutense de Madrid» es nombre propio completo (RAE, §4.4).',
    dificultad: 3,
  },
  {
    categoria: 'mayusculas',
    enunciado: '¿Cuál de las siguientes frases usa CORRECTAMENTE las mayúsculas?',
    opciones: [
      'Habla Inglés y Francés con fluidez.',
      'habla inglés y francés con fluidez.',
      'Habla inglés y francés con fluidez.',
      'Habla Inglés y francés con Fluidez.',
    ],
    correcta: 2,
    explicacion: 'Los nombres de idiomas se escriben en minúscula en español (RAE, §4.6).',
    dificultad: 3,
  },
  {
    categoria: 'mayusculas',
    enunciado: '¿Cuál de las siguientes frases usa CORRECTAMENTE las mayúsculas?',
    opciones: [
      'La Tierra gira alrededor del sol.',
      'La tierra gira alrededor del Sol.',
      'La Tierra gira alrededor del Sol.',
      'la tierra gira alrededor del sol.',
    ],
    correcta: 2,
    explicacion: '«Tierra» y «Sol» se escriben con mayúscula cuando se refieren a los astros en contexto astronómico (RAE, §4.5).',
    dificultad: 3,
  },
  {
    categoria: 'mayusculas',
    enunciado: '¿Cuál de las siguientes frases usa CORRECTAMENTE las mayúsculas?',
    opciones: [
      'El señor García es Abogado.',
      'El Señor García es abogado.',
      'El señor García es abogado.',
      'el señor garcía es abogado.',
    ],
    correcta: 2,
    explicacion: 'Los tratamientos (señor, don) y las profesiones (abogado) van en minúscula. Los apellidos van en mayúscula (RAE, §4.3).',
    dificultad: 2,
  },
  {
    categoria: 'mayusculas',
    enunciado: '¿Cuál de las siguientes frases usa CORRECTAMENTE las mayúsculas?',
    opciones: [
      'La guerra civil española terminó en 1939.',
      'La Guerra Civil española terminó en 1939.',
      'La Guerra civil Española terminó en 1939.',
      'la Guerra Civil Española terminó en 1939.',
    ],
    correcta: 1,
    explicacion: '«Guerra Civil» lleva mayúsculas como nombre de acontecimiento histórico. «Española» como adjetivo especificativo va en minúscula (RAE, §4.4).',
    dificultad: 3,
  },
]

// ─── PUNTUACIÓN (~25 ítems) ─────────────────────────────────────────────────

const PUNTUACION: OrtografiaItem[] = [
  // Dificultad 1
  {
    categoria: 'puntuacion',
    enunciado: 'Señale la frase con la puntuación CORRECTA:',
    opciones: [
      'Compré manzanas, peras, plátanos y uvas.',
      'Compré manzanas peras plátanos y uvas.',
      'Compré, manzanas, peras, plátanos, y uvas.',
      'Compré manzanas, peras, plátanos, y, uvas.',
    ],
    correcta: 0,
    explicacion: 'En enumeraciones, los elementos se separan con coma excepto los dos últimos, que van unidos por «y» sin coma (RAE, §5.1).',
    dificultad: 1,
  },
  {
    categoria: 'puntuacion',
    enunciado: 'Señale la frase con la puntuación CORRECTA:',
    opciones: [
      'El perro, comió su comida.',
      'El perro comió su comida.',
      'El perro comió, su comida.',
      'El, perro comió su comida.',
    ],
    correcta: 1,
    explicacion: 'No se pone coma entre sujeto y predicado (RAE, §5.1).',
    dificultad: 1,
  },
  {
    categoria: 'puntuacion',
    enunciado: 'Señale la frase con la puntuación CORRECTA:',
    opciones: [
      'Me gusta leer. Sin embargo no tengo tiempo.',
      'Me gusta leer, sin embargo, no tengo tiempo.',
      'Me gusta leer sin embargo no tengo tiempo.',
      'Me gusta leer; sin embargo no tengo tiempo.',
    ],
    correcta: 1,
    explicacion: '«Sin embargo» es un conector que va entre comas cuando va intercalado (RAE, §5.2).',
    dificultad: 1,
  },
  {
    categoria: 'puntuacion',
    enunciado: 'Señale la frase con la puntuación CORRECTA:',
    opciones: [
      'Hoy es lunes mañana será martes.',
      'Hoy es lunes. Mañana será martes.',
      'Hoy es lunes, Mañana será martes.',
      'Hoy, es lunes. mañana será martes.',
    ],
    correcta: 1,
    explicacion: 'Dos oraciones independientes se separan con punto. Tras punto va mayúscula (RAE, §5.4).',
    dificultad: 1,
  },
  {
    categoria: 'puntuacion',
    enunciado: 'Señale la frase con la puntuación CORRECTA:',
    opciones: [
      'María estudia derecho, Pedro, medicina.',
      'María estudia derecho Pedro medicina.',
      'María, estudia derecho Pedro medicina.',
      'María estudia derecho. Pedro medicina.',
    ],
    correcta: 0,
    explicacion: 'Coma entre las dos oraciones (yuxtapuestas) y coma que sustituye al verbo elidido «estudia» (RAE, §5.1.3).',
    dificultad: 1,
  },
  {
    categoria: 'puntuacion',
    enunciado: 'Señale la frase con la puntuación CORRECTA:',
    opciones: [
      'Querido, Juan: Te escribo para saludarte.',
      'Querido Juan: te escribo para saludarte.',
      'Querido Juan: Te escribo para saludarte.',
      'Querido Juan te escribo para saludarte.',
    ],
    correcta: 2,
    explicacion: 'Tras el saludo en una carta van dos puntos y la siguiente palabra empieza con mayúscula (RAE, §5.7).',
    dificultad: 1,
  },
  {
    categoria: 'puntuacion',
    enunciado: 'Señale la frase con la puntuación CORRECTA:',
    opciones: [
      'No sé, qué hacer.',
      'No sé qué hacer.',
      'No, sé qué hacer.',
      'No sé que, hacer.',
    ],
    correcta: 1,
    explicacion: 'No se pone coma entre el verbo y su complemento directo (RAE, §5.1).',
    dificultad: 1,
  },
  // Dificultad 2
  {
    categoria: 'puntuacion',
    enunciado: 'Señale la frase con la puntuación CORRECTA:',
    opciones: [
      'Juan ven aquí.',
      'Juan, ven aquí.',
      'Juan: ven aquí.',
      'Juan; ven aquí.',
    ],
    correcta: 1,
    explicacion: 'El vocativo (llamada directa a una persona) se separa con coma: «Juan, ven aquí» (RAE, §5.1.2).',
    dificultad: 2,
  },
  {
    categoria: 'puntuacion',
    enunciado: 'Señale la frase con la puntuación CORRECTA:',
    opciones: [
      'Es decir que no vendrá.',
      'Es decir, que no vendrá.',
      'Es, decir que no vendrá.',
      'Es decir; que no vendrá.',
    ],
    correcta: 1,
    explicacion: '«Es decir» es un conector explicativo que va seguido de coma (RAE, §5.2).',
    dificultad: 2,
  },
  {
    categoria: 'puntuacion',
    enunciado: 'Señale la frase con la puntuación CORRECTA:',
    opciones: [
      'Unos trabajan, otros descansan.',
      'Unos trabajan; otros descansan.',
      'Unos trabajan otros descansan.',
      'Unos trabajan. otros descansan.',
    ],
    correcta: 1,
    explicacion: 'El punto y coma separa oraciones yuxtapuestas que mantienen relación semántica entre sí (RAE, §5.3).',
    dificultad: 2,
  },
  {
    categoria: 'puntuacion',
    enunciado: 'Señale la frase con la puntuación CORRECTA:',
    opciones: [
      'Madrid capital de España es una gran ciudad.',
      'Madrid, capital de España, es una gran ciudad.',
      'Madrid capital de España, es una gran ciudad.',
      'Madrid, capital de España es una gran ciudad.',
    ],
    correcta: 1,
    explicacion: 'La aposición explicativa («capital de España») va entre comas (RAE, §5.1.1).',
    dificultad: 2,
  },
  {
    categoria: 'puntuacion',
    enunciado: 'Señale la frase con la puntuación CORRECTA:',
    opciones: [
      'Cuando llegues, llámame.',
      'Cuando llegues llámame.',
      'Cuando, llegues llámame.',
      'Cuando llegues; llámame.',
    ],
    correcta: 0,
    explicacion: 'Cuando la subordinada temporal antecede a la principal, se separan con coma (RAE, §5.1.4).',
    dificultad: 2,
  },
  {
    categoria: 'puntuacion',
    enunciado: 'Señale la frase con la puntuación CORRECTA:',
    opciones: [
      'Dijo, que vendría mañana.',
      'Dijo que, vendría mañana.',
      'Dijo que vendría mañana.',
      'Dijo: que vendría mañana.',
    ],
    correcta: 2,
    explicacion: 'No se pone coma entre el verbo y la conjunción «que» que introduce su complemento (RAE, §5.1).',
    dificultad: 2,
  },
  {
    categoria: 'puntuacion',
    enunciado: 'Señale la frase con la puntuación CORRECTA:',
    opciones: [
      'No obstante el proyecto sigue adelante.',
      'No obstante, el proyecto sigue adelante.',
      'No obstante; el proyecto sigue adelante.',
      'No, obstante, el proyecto sigue adelante.',
    ],
    correcta: 1,
    explicacion: '«No obstante» como conector va seguido de coma (RAE, §5.2).',
    dificultad: 2,
  },
  // Dificultad 3
  {
    categoria: 'puntuacion',
    enunciado: 'Señale la frase con la puntuación CORRECTA:',
    opciones: [
      'El testigo declaró: «No vi nada».',
      'El testigo declaró: «No vi nada.»',
      'El testigo declaró «No vi nada».',
      'El testigo declaró, «No vi nada».',
    ],
    correcta: 0,
    explicacion: 'Tras los dos puntos se abren comillas para citas textuales. El punto final va fuera de las comillas de cierre (RAE, §5.8).',
    dificultad: 3,
  },
  {
    categoria: 'puntuacion',
    enunciado: 'Señale la frase con la puntuación CORRECTA:',
    opciones: [
      '—¿Vienes? —preguntó María.',
      '— ¿Vienes? — preguntó María.',
      '-¿Vienes?- preguntó María.',
      '«¿Vienes?», preguntó María.',
    ],
    correcta: 0,
    explicacion: 'En diálogos, la raya larga (—) va pegada al texto que introduce, sin espacio. La segunda raya también va pegada al inciso (RAE, §5.9).',
    dificultad: 3,
  },
  {
    categoria: 'puntuacion',
    enunciado: 'Señale la frase con la puntuación CORRECTA:',
    opciones: [
      'Hay tres tipos de triángulos: equilátero, isósceles y escaleno.',
      'Hay tres tipos de triángulos, equilátero, isósceles y escaleno.',
      'Hay tres tipos de triángulos; equilátero, isósceles y escaleno.',
      'Hay tres tipos de triángulos equilátero, isósceles y escaleno.',
    ],
    correcta: 0,
    explicacion: 'Los dos puntos introducen una enumeración que explica lo anterior (RAE, §5.7).',
    dificultad: 3,
  },
  {
    categoria: 'puntuacion',
    enunciado: 'Señale la frase con la puntuación CORRECTA:',
    opciones: [
      'Su hermano —el mayor— vive en París.',
      'Su hermano, —el mayor—, vive en París.',
      'Su hermano —el mayor,— vive en París.',
      'Su hermano —el mayor— vive, en París.',
    ],
    correcta: 0,
    explicacion: 'Los incisos entre rayas no necesitan comas adicionales (RAE, §5.9).',
    dificultad: 3,
  },
  {
    categoria: 'puntuacion',
    enunciado: 'Señale la frase con la puntuación CORRECTA:',
    opciones: [
      'No es fácil, ¿verdad?',
      'No es fácil ¿Verdad?',
      'No es fácil. ¿verdad?',
      '¿No es fácil, verdad?',
    ],
    correcta: 0,
    explicacion: 'La pregunta coletilla se separa con coma y empieza con minúscula tras la coma (RAE, §5.10).',
    dificultad: 3,
  },
  {
    categoria: 'puntuacion',
    enunciado: 'Señale la frase con la puntuación CORRECTA:',
    opciones: [
      'Estimado Sr. García: Le comunico que...',
      'Estimado Sr. García, Le comunico que...',
      'Estimado Sr. García; Le comunico que...',
      'Estimado Sr. García. Le comunico que...',
    ],
    correcta: 0,
    explicacion: 'El saludo en cartas formales termina con dos puntos (no coma ni punto). La frase siguiente empieza con mayúscula (RAE, §5.7).',
    dificultad: 3,
  },
  {
    categoria: 'puntuacion',
    enunciado: 'Señale la frase con la puntuación CORRECTA:',
    opciones: [
      'El acusado que estaba nervioso, confesó.',
      'El acusado, que estaba nervioso confesó.',
      'El acusado, que estaba nervioso, confesó.',
      'El acusado que estaba nervioso confesó.',
    ],
    correcta: 2,
    explicacion: 'La oración de relativo explicativa («que estaba nervioso») va entre comas (RAE, §5.1.1).',
    dificultad: 3,
  },
  {
    categoria: 'puntuacion',
    enunciado: 'Señale la frase con la puntuación CORRECTA:',
    opciones: [
      'Por ejemplo: el agua hierve a 100 °C.',
      'Por ejemplo, el agua hierve a 100 °C.',
      'Por ejemplo; el agua hierve a 100 °C.',
      'Por ejemplo el agua hierve a 100 °C.',
    ],
    correcta: 1,
    explicacion: '«Por ejemplo» como conector va seguido de coma (no de dos puntos) cuando introduce la información directamente (RAE, §5.2).',
    dificultad: 3,
  },
  {
    categoria: 'puntuacion',
    enunciado: 'Señale la frase con la puntuación CORRECTA:',
    opciones: [
      'Necesito: pan, leche y huevos.',
      'Necesito pan, leche y huevos.',
      'Necesito, pan leche y huevos.',
      'Necesito; pan, leche y huevos.',
    ],
    correcta: 1,
    explicacion: 'No se ponen dos puntos entre el verbo y sus complementos directos. La enumeración va separada por comas (RAE, §5.7).',
    dificultad: 2,
  },
  {
    categoria: 'puntuacion',
    enunciado: 'Señale la frase con la puntuación CORRECTA:',
    opciones: [
      'Aunque llovía salimos a pasear.',
      'Aunque llovía, salimos a pasear.',
      'Aunque, llovía salimos a pasear.',
      'Aunque llovía; salimos a pasear.',
    ],
    correcta: 1,
    explicacion: 'Cuando la subordinada concesiva antecede a la principal, se separan con coma (RAE, §5.1.4).',
    dificultad: 2,
  },
  {
    categoria: 'puntuacion',
    enunciado: 'Señale la frase con la puntuación CORRECTA:',
    opciones: [
      'En efecto el resultado fue positivo.',
      'En efecto, el resultado fue positivo.',
      'En efecto; el resultado fue positivo.',
      'En, efecto, el resultado fue positivo.',
    ],
    correcta: 1,
    explicacion: '«En efecto» es un conector que va seguido de coma (RAE, §5.2).',
    dificultad: 1,
  },
]

// ─── HOMÓFONOS (~25 ítems) ──────────────────────────────────────────────────

const HOMOFONOS: OrtografiaItem[] = [
  // Dificultad 1
  {
    categoria: 'homofonos',
    enunciado: 'Complete: «______ muchas personas en la sala.»',
    opciones: ['Hay', 'Ahí', 'Ay', 'Ahi'],
    correcta: 0,
    explicacion: '«Hay» (verbo haber impersonal). «Ahí» (adverbio de lugar). «Ay» (interjección de dolor).',
    dificultad: 1,
  },
  {
    categoria: 'homofonos',
    enunciado: 'Complete: «Deja las llaves ______.»',
    opciones: ['hay', 'ahí', 'ay', 'ahi'],
    correcta: 1,
    explicacion: '«Ahí» (adverbio de lugar, con tilde). «Hay» (verbo haber). «Ay» (interjección).',
    dificultad: 1,
  },
  {
    categoria: 'homofonos',
    enunciado: 'Complete: «¡______, qué dolor!»',
    opciones: ['Hay', 'Ahí', 'Ay', 'Ahi'],
    correcta: 2,
    explicacion: '«Ay» es interjección que expresa dolor o sorpresa.',
    dificultad: 1,
  },
  {
    categoria: 'homofonos',
    enunciado: 'Complete: «Vamos ______ si es verdad.»',
    opciones: ['haber', 'a ver', 'haver', 'a ber'],
    correcta: 1,
    explicacion: '«A ver» (preposición + infinitivo de ver) se usa para comprobar. «Haber» es verbo auxiliar.',
    dificultad: 1,
  },
  {
    categoria: 'homofonos',
    enunciado: 'Complete: «Debería ______ llegado antes.»',
    opciones: ['a ver', 'haber', 'haver', 'a ber'],
    correcta: 1,
    explicacion: '«Haber» es verbo auxiliar en tiempos compuestos: «debería haber llegado».',
    dificultad: 1,
  },
  {
    categoria: 'homofonos',
    enunciado: 'Complete: «______ que estudiar más.»',
    opciones: ['A', 'Ha', 'Ah', 'Há'],
    correcta: 1,
    explicacion: '«Ha» es verbo haber: «ha que» = «hay que». «A» es preposición. «Ah» es interjección.',
    dificultad: 1,
  },
  {
    categoria: 'homofonos',
    enunciado: 'Complete: «Voy ______ la tienda.»',
    opciones: ['ha', 'a', 'ah', 'há'],
    correcta: 1,
    explicacion: '«A» es preposición de dirección. «Ha» es verbo haber.',
    dificultad: 1,
  },
  {
    categoria: 'homofonos',
    enunciado: 'Complete: «¡______, ya entiendo!»',
    opciones: ['Ha', 'A', 'Ah', 'Há'],
    correcta: 2,
    explicacion: '«Ah» es interjección que expresa comprensión o sorpresa.',
    dificultad: 1,
  },
  // Dificultad 2
  {
    categoria: 'homofonos',
    enunciado: 'Complete: «Espero que ______ al partido mañana.»',
    opciones: ['vaya', 'valla', 'baya', 'balla'],
    correcta: 0,
    explicacion: '«Vaya» (subjuntivo de ir). «Valla» (cercado). «Baya» (fruto silvestre).',
    dificultad: 2,
  },
  {
    categoria: 'homofonos',
    enunciado: 'Complete: «El jardinero pintó la ______ de blanco.»',
    opciones: ['vaya', 'valla', 'baya', 'balla'],
    correcta: 1,
    explicacion: '«Valla» (cercado, empalizada) con v y ll.',
    dificultad: 2,
  },
  {
    categoria: 'homofonos',
    enunciado: 'Complete: «Espero que no ______ problemas.»',
    opciones: ['haya', 'halla', 'aya', 'alla'],
    correcta: 0,
    explicacion: '«Haya» (subjuntivo de haber). «Halla» (de hallar, encontrar). «Aya» (niñera).',
    dificultad: 2,
  },
  {
    categoria: 'homofonos',
    enunciado: 'Complete: «La policía ______ nuevas pruebas.»',
    opciones: ['haya', 'halla', 'aya', 'alla'],
    correcta: 1,
    explicacion: '«Halla» (del verbo hallar = encontrar). «Haya» (subjuntivo de haber).',
    dificultad: 2,
  },
  {
    categoria: 'homofonos',
    enunciado: 'Complete: «La ______ del roble es muy valorada.»',
    opciones: ['bota', 'vota', 'bóta', 'vóta'],
    correcta: 0,
    explicacion: '«Bota» (calzado o recipiente de vino). «Vota» (del verbo votar). Aquí no se refiere a árbol.',
    dificultad: 2,
  },
  {
    categoria: 'homofonos',
    enunciado: 'Complete: «El ciudadano ______ en las elecciones.»',
    opciones: ['bota', 'vota', 'bóta', 'vóta'],
    correcta: 1,
    explicacion: '«Vota» (del verbo votar, emitir un voto). «Bota» (calzado).',
    dificultad: 2,
  },
  {
    categoria: 'homofonos',
    enunciado: 'Complete: «No ______ bien lo que dice el cartel.»',
    opciones: ['ves', 'vez', 'bés', 'béz'],
    correcta: 0,
    explicacion: '«Ves» (del verbo ver). «Vez» (ocasión, momento).',
    dificultad: 2,
  },
  {
    categoria: 'homofonos',
    enunciado: 'Complete: «Esta ______ me toca a mí.»',
    opciones: ['ves', 'vez', 'bés', 'béz'],
    correcta: 1,
    explicacion: '«Vez» (sustantivo: ocasión). «Ves» (verbo ver).',
    dificultad: 2,
  },
  // Dificultad 3
  {
    categoria: 'homofonos',
    enunciado: 'Complete: «Los ciudadanos se ______ contra la injusticia.»',
    opciones: ['rebelaron', 'revelaron', 'revalaron', 'rebelàron'],
    correcta: 0,
    explicacion: '«Rebelarse» (sublevarse) con b. «Revelar» (descubrir un secreto, o fotografía) con v.',
    dificultad: 3,
  },
  {
    categoria: 'homofonos',
    enunciado: 'Complete: «Las pruebas ______ la verdad.»',
    opciones: ['rebelaron', 'revelaron', 'revalaron', 'reveláron'],
    correcta: 1,
    explicacion: '«Revelar» (descubrir, poner de manifiesto) con v. «Rebelar» (sublevar) con b.',
    dificultad: 3,
  },
  {
    categoria: 'homofonos',
    enunciado: 'Complete: «La ______ del árbol cura enfermedades.»',
    opciones: ['sabia', 'savia', 'sabía', 'savía'],
    correcta: 1,
    explicacion: '«Savia» (líquido de las plantas) con v. «Sabia» (que sabe mucho) con b.',
    dificultad: 3,
  },
  {
    categoria: 'homofonos',
    enunciado: 'Complete: «Mi abuela es muy ______.»',
    opciones: ['savia', 'sabia', 'sabía', 'savía'],
    correcta: 1,
    explicacion: '«Sabia» (adjetivo: que tiene sabiduría) con b. «Savia» (líquido vegetal) con v.',
    dificultad: 3,
  },
  {
    categoria: 'homofonos',
    enunciado: 'Complete: «El Estado puede ______ los impuestos.»',
    opciones: ['grabar', 'gravar', 'gravár', 'grabár'],
    correcta: 1,
    explicacion: '«Gravar» (imponer impuestos o cargas) con v. «Grabar» (registrar sonido/imagen) con b.',
    dificultad: 3,
  },
  {
    categoria: 'homofonos',
    enunciado: 'Complete: «Voy a ______ la conversación.»',
    opciones: ['gravar', 'grabar', 'gravár', 'grabár'],
    correcta: 1,
    explicacion: '«Grabar» (registrar sonido o imagen) con b. «Gravar» (imponer un gravamen) con v.',
    dificultad: 3,
  },
  {
    categoria: 'homofonos',
    enunciado: 'Complete: «El juez va a ______ la sentencia.»',
    opciones: ['rebocar', 'revocar', 'rebocár', 'revocár'],
    correcta: 1,
    explicacion: '«Revocar» (anular, dejar sin efecto) con v. «Rebocar» (no es palabra estándar; «rebozar» es la correcta para cubrir con algo).',
    dificultad: 3,
  },
  {
    categoria: 'homofonos',
    enunciado: 'Complete: «El soldado juró ______ a la bandera.»',
    opciones: ['reverenciar', 'reberenciar', 'reverensiar', 'rebérenciar'],
    correcta: 0,
    explicacion: '«Reverenciar» se escribe con v y c (del latín reverentia).',
    dificultad: 3,
  },
  {
    categoria: 'homofonos',
    enunciado: 'Complete: «No conviene ______ esa herida.»',
    opciones: ['escarbar', 'escarvar', 'escarbár', 'escarvár'],
    correcta: 0,
    explicacion: '«Escarbar» se escribe con b (del latín exscalpĕre → escarbar).',
    dificultad: 3,
  },
]

// ─── EXPORT: banco completo ─────────────────────────────────────────────────

export const ORTOGRAFIA_BANK: readonly OrtografiaItem[] = [
  ...ACENTUACION,
  ...B_V,
  ...H_ITEMS,
  ...G_J,
  ...LL_Y,
  ...C_Z_S,
  ...MAYUSCULAS,
  ...PUNTUACION,
  ...HOMOFONOS,
] as const
