/**
 * lib/ingles/bank.ts — §6.6
 *
 * Banco de preguntas de ingles A2-B1 para Guardia Civil.
 * ~170 items organizados por categoria y dificultad.
 */

import type { InglesItem } from './types'

// ---------------------------------------------------------------------------
// grammar_tenses (~25 items)
// ---------------------------------------------------------------------------
const grammarTenses: InglesItem[] = [
  // Dificultad 1 — Present simple / continuous
  {
    categoria: 'grammar_tenses',
    enunciado: 'She ___ to work every day.',
    opciones: ['goes', 'go', 'going', 'gone'],
    correcta: 0,
    explicacion: 'Tercera persona del singular en present simple: se anade -es a "go" -> "goes".',
    dificultad: 1,
  },
  {
    categoria: 'grammar_tenses',
    enunciado: 'They ___ football right now.',
    opciones: ['plays', 'are playing', 'play', 'played'],
    correcta: 1,
    explicacion: '"Right now" indica una accion en curso -> present continuous: are playing.',
    dificultad: 1,
  },
  {
    categoria: 'grammar_tenses',
    enunciado: 'My brother ___ coffee every morning.',
    opciones: ['drink', 'drinks', 'is drinking', 'drank'],
    correcta: 1,
    explicacion: '"Every morning" indica habito -> present simple. Tercera persona: drinks.',
    dificultad: 1,
  },
  {
    categoria: 'grammar_tenses',
    enunciado: 'Look! The children ___ in the park.',
    opciones: ['run', 'runs', 'are running', 'ran'],
    correcta: 2,
    explicacion: '"Look!" senala algo que ocurre ahora mismo -> present continuous: are running.',
    dificultad: 1,
  },
  {
    categoria: 'grammar_tenses',
    enunciado: 'Water ___ at 100 degrees Celsius.',
    opciones: ['boils', 'is boiling', 'boil', 'boiled'],
    correcta: 0,
    explicacion: 'Verdades universales usan present simple. Tercera persona: boils.',
    dificultad: 1,
  },
  {
    categoria: 'grammar_tenses',
    enunciado: 'I ___ English twice a week.',
    opciones: ['am studying', 'studies', 'study', 'studied'],
    correcta: 2,
    explicacion: '"Twice a week" indica frecuencia habitual -> present simple: study.',
    dificultad: 1,
  },
  {
    categoria: 'grammar_tenses',
    enunciado: 'Be quiet! The baby ___.',
    opciones: ['sleeps', 'is sleeping', 'sleep', 'slept'],
    correcta: 1,
    explicacion: 'Accion en progreso ahora mismo -> present continuous: is sleeping.',
    dificultad: 1,
  },
  {
    categoria: 'grammar_tenses',
    enunciado: 'The train ___ at 9 o\'clock every morning.',
    opciones: ['leave', 'is leaving', 'leaves', 'left'],
    correcta: 2,
    explicacion: 'Horarios fijos usan present simple. Tercera persona: leaves.',
    dificultad: 1,
  },
  // Dificultad 2 — Past simple vs present perfect
  {
    categoria: 'grammar_tenses',
    enunciado: 'I ___ there last year.',
    opciones: ['went', 'have gone', 'go', 'has gone'],
    correcta: 0,
    explicacion: '"Last year" es un momento concreto del pasado -> past simple: went.',
    dificultad: 2,
  },
  {
    categoria: 'grammar_tenses',
    enunciado: 'She ___ in London since 2015.',
    opciones: ['lives', 'lived', 'has lived', 'is living'],
    correcta: 2,
    explicacion: '"Since 2015" indica una accion que empezo en el pasado y continua -> present perfect: has lived.',
    dificultad: 2,
  },
  {
    categoria: 'grammar_tenses',
    enunciado: 'We ___ the film yesterday.',
    opciones: ['have seen', 'saw', 'see', 'seen'],
    correcta: 1,
    explicacion: '"Yesterday" indica un momento concreto del pasado -> past simple: saw.',
    dificultad: 2,
  },
  {
    categoria: 'grammar_tenses',
    enunciado: 'They ___ already ___ lunch.',
    opciones: ['have / eaten', 'has / eaten', 'did / eat', 'were / eating'],
    correcta: 0,
    explicacion: '"Already" se usa con present perfect. Sujeto plural: have already eaten.',
    dificultad: 2,
  },
  {
    categoria: 'grammar_tenses',
    enunciado: 'I ___ never ___ to Japan.',
    opciones: ['have / been', 'has / been', 'did / be', 'was / being'],
    correcta: 0,
    explicacion: '"Never" con experiencias de vida usa present perfect: have never been.',
    dificultad: 2,
  },
  {
    categoria: 'grammar_tenses',
    enunciado: 'He ___ his keys two hours ago.',
    opciones: ['has lost', 'lost', 'loses', 'is losing'],
    correcta: 1,
    explicacion: '"Two hours ago" indica momento concreto -> past simple: lost.',
    dificultad: 2,
  },
  {
    categoria: 'grammar_tenses',
    enunciado: 'How long ___ you ___ your car?',
    opciones: ['have / had', 'did / have', 'do / have', 'are / having'],
    correcta: 0,
    explicacion: '"How long" pregunta por duracion desde el pasado hasta ahora -> present perfect: have you had.',
    dificultad: 2,
  },
  {
    categoria: 'grammar_tenses',
    enunciado: 'She ___ to Madrid when she was a child.',
    opciones: ['has moved', 'moved', 'moves', 'is moving'],
    correcta: 1,
    explicacion: '"When she was a child" situa la accion en el pasado -> past simple: moved.',
    dificultad: 2,
  },
  // Dificultad 3 — Past perfect, future continuous
  {
    categoria: 'grammar_tenses',
    enunciado: 'By the time we arrived, they ___.',
    opciones: ['had left', 'left', 'have left', 'were leaving'],
    correcta: 0,
    explicacion: '"By the time" + pasado indica anterioridad a otro momento pasado -> past perfect: had left.',
    dificultad: 3,
  },
  {
    categoria: 'grammar_tenses',
    enunciado: 'This time tomorrow, I ___ on the beach.',
    opciones: ['will lie', 'will be lying', 'am lying', 'lie'],
    correcta: 1,
    explicacion: '"This time tomorrow" indica una accion en progreso en un momento futuro -> future continuous: will be lying.',
    dificultad: 3,
  },
  {
    categoria: 'grammar_tenses',
    enunciado: 'She told me she ___ the report before the meeting.',
    opciones: ['had finished', 'finished', 'has finished', 'finishes'],
    correcta: 0,
    explicacion: 'Accion anterior a otra pasada (reported speech) -> past perfect: had finished.',
    dificultad: 3,
  },
  {
    categoria: 'grammar_tenses',
    enunciado: 'At 8 PM tonight, we ___ dinner.',
    opciones: ['will have', 'will be having', 'have', 'are have'],
    correcta: 1,
    explicacion: 'Accion en curso en un momento futuro especifico -> future continuous: will be having.',
    dificultad: 3,
  },
  {
    categoria: 'grammar_tenses',
    enunciado: 'After he ___ the door, he realised he had forgotten his keys.',
    opciones: ['had closed', 'closed', 'has closed', 'was closing'],
    correcta: 0,
    explicacion: 'Dos acciones pasadas: la primera usa past perfect (had closed), la segunda past simple.',
    dificultad: 3,
  },
  {
    categoria: 'grammar_tenses',
    enunciado: 'By next June, I ___ at this company for ten years.',
    opciones: ['will work', 'will have worked', 'work', 'am working'],
    correcta: 1,
    explicacion: '"By next June" + duracion -> future perfect: will have worked.',
    dificultad: 3,
  },
  {
    categoria: 'grammar_tenses',
    enunciado: 'I ___ the book before the film came out.',
    opciones: ['had read', 'read', 'have read', 'was reading'],
    correcta: 0,
    explicacion: 'Accion completada antes de otro evento pasado -> past perfect: had read.',
    dificultad: 3,
  },
  {
    categoria: 'grammar_tenses',
    enunciado: 'Don\'t call me at 3. I ___ an exam then.',
    opciones: ['will take', 'will be taking', 'take', 'am taking'],
    correcta: 1,
    explicacion: 'Accion en progreso en un momento futuro concreto -> future continuous: will be taking.',
    dificultad: 3,
  },
  {
    categoria: 'grammar_tenses',
    enunciado: 'When I got home, someone ___ into my flat.',
    opciones: ['had broken', 'broke', 'has broken', 'breaks'],
    correcta: 0,
    explicacion: 'El robo ocurrio antes de llegar a casa -> past perfect: had broken.',
    dificultad: 3,
  },
]

// ---------------------------------------------------------------------------
// grammar_prepositions (~20 items)
// ---------------------------------------------------------------------------
const grammarPrepositions: InglesItem[] = [
  // Dificultad 1 — Basic in/on/at
  {
    categoria: 'grammar_prepositions',
    enunciado: 'The meeting is ___ Monday.',
    opciones: ['in', 'on', 'at', 'by'],
    correcta: 1,
    explicacion: 'Se usa "on" con dias de la semana: on Monday.',
    dificultad: 1,
  },
  {
    categoria: 'grammar_prepositions',
    enunciado: 'She was born ___ 1995.',
    opciones: ['on', 'at', 'in', 'to'],
    correcta: 2,
    explicacion: 'Se usa "in" con anos: in 1995.',
    dificultad: 1,
  },
  {
    categoria: 'grammar_prepositions',
    enunciado: 'The class starts ___ 9 o\'clock.',
    opciones: ['in', 'on', 'at', 'for'],
    correcta: 2,
    explicacion: 'Se usa "at" con horas concretas: at 9 o\'clock.',
    dificultad: 1,
  },
  {
    categoria: 'grammar_prepositions',
    enunciado: 'There is a picture ___ the wall.',
    opciones: ['in', 'on', 'at', 'by'],
    correcta: 1,
    explicacion: 'Se usa "on" para superficies: on the wall.',
    dificultad: 1,
  },
  {
    categoria: 'grammar_prepositions',
    enunciado: 'He lives ___ a small village.',
    opciones: ['on', 'at', 'in', 'to'],
    correcta: 2,
    explicacion: 'Se usa "in" con ciudades, pueblos y paises: in a small village.',
    dificultad: 1,
  },
  {
    categoria: 'grammar_prepositions',
    enunciado: 'I\'ll see you ___ Christmas.',
    opciones: ['in', 'on', 'at', 'by'],
    correcta: 2,
    explicacion: 'Se usa "at" con festividades: at Christmas, at Easter.',
    dificultad: 1,
  },
  {
    categoria: 'grammar_prepositions',
    enunciado: 'We arrived ___ the airport early.',
    opciones: ['to', 'in', 'at', 'on'],
    correcta: 2,
    explicacion: 'Se usa "at" con lugares especificos como puntos: at the airport.',
    dificultad: 1,
  },
  // Dificultad 2 — Phrasal verbs
  {
    categoria: 'grammar_prepositions',
    enunciado: 'Can you look ___ the children while I\'m out?',
    opciones: ['after', 'for', 'at', 'up'],
    correcta: 0,
    explicacion: '"Look after" = cuidar de alguien. "Look for" = buscar. "Look at" = mirar.',
    dificultad: 2,
  },
  {
    categoria: 'grammar_prepositions',
    enunciado: 'He decided to give ___ smoking.',
    opciones: ['in', 'out', 'up', 'away'],
    correcta: 2,
    explicacion: '"Give up" = dejar, abandonar un habito. Es un phrasal verb muy comun.',
    dificultad: 2,
  },
  {
    categoria: 'grammar_prepositions',
    enunciado: 'The firefighters put ___ the fire quickly.',
    opciones: ['off', 'on', 'out', 'up'],
    correcta: 2,
    explicacion: '"Put out" = apagar (un fuego). "Put off" = posponer. "Put on" = ponerse (ropa).',
    dificultad: 2,
  },
  {
    categoria: 'grammar_prepositions',
    enunciado: 'I ran ___ an old friend at the supermarket.',
    opciones: ['after', 'into', 'out', 'over'],
    correcta: 1,
    explicacion: '"Run into" = encontrarse con alguien por casualidad.',
    dificultad: 2,
  },
  {
    categoria: 'grammar_prepositions',
    enunciado: 'Please turn ___ the lights when you leave.',
    opciones: ['on', 'up', 'off', 'in'],
    correcta: 2,
    explicacion: '"Turn off" = apagar (luces, aparatos). "Turn on" = encender.',
    dificultad: 2,
  },
  {
    categoria: 'grammar_prepositions',
    enunciado: 'We need to find ___ what happened.',
    opciones: ['up', 'out', 'in', 'off'],
    correcta: 1,
    explicacion: '"Find out" = descubrir, averiguar informacion.',
    dificultad: 2,
  },
  {
    categoria: 'grammar_prepositions',
    enunciado: 'She takes ___ her mother. They look very similar.',
    opciones: ['after', 'off', 'on', 'up'],
    correcta: 0,
    explicacion: '"Take after" = parecerse a un familiar.',
    dificultad: 2,
  },
  // Dificultad 3 — Dependent prepositions
  {
    categoria: 'grammar_prepositions',
    enunciado: 'She is very interested ___ art.',
    opciones: ['on', 'in', 'at', 'for'],
    correcta: 1,
    explicacion: '"Interested in" es la preposicion dependiente correcta. Error comun del espanol: *interested on.',
    dificultad: 3,
  },
  {
    categoria: 'grammar_prepositions',
    enunciado: 'He is responsible ___ the security of the building.',
    opciones: ['of', 'about', 'for', 'with'],
    correcta: 2,
    explicacion: '"Responsible for" = responsable de. Error comun: *responsible of (influencia del espanol "responsable de").',
    dificultad: 3,
  },
  {
    categoria: 'grammar_prepositions',
    enunciado: 'I am good ___ mathematics.',
    opciones: ['in', 'at', 'for', 'on'],
    correcta: 1,
    explicacion: '"Good at" = bueno en (una habilidad). Error comun del espanol: *good in.',
    dificultad: 3,
  },
  {
    categoria: 'grammar_prepositions',
    enunciado: 'The decision depends ___ many factors.',
    opciones: ['of', 'on', 'in', 'from'],
    correcta: 1,
    explicacion: '"Depend on" = depender de. Error comun: *depend of (del espanol "depender de").',
    dificultad: 3,
  },
  {
    categoria: 'grammar_prepositions',
    enunciado: 'He apologised ___ being late.',
    opciones: ['about', 'for', 'of', 'to'],
    correcta: 1,
    explicacion: '"Apologise for" = disculparse por algo.',
    dificultad: 3,
  },
  {
    categoria: 'grammar_prepositions',
    enunciado: 'I\'m not used ___ getting up so early.',
    opciones: ['for', 'at', 'to', 'of'],
    correcta: 2,
    explicacion: '"Used to" + gerundio = estar acostumbrado a. No confundir con "used to" + infinitivo (solia).',
    dificultad: 3,
  },
]

// ---------------------------------------------------------------------------
// grammar_articles (~15 items)
// ---------------------------------------------------------------------------
const grammarArticles: InglesItem[] = [
  // Dificultad 1 — a/an/the basic
  {
    categoria: 'grammar_articles',
    enunciado: 'She is ___ teacher.',
    opciones: ['a', 'an', 'the', '(no article)'],
    correcta: 0,
    explicacion: 'Profesiones con "a/an": She is a teacher. Se usa "a" antes de consonante.',
    dificultad: 1,
  },
  {
    categoria: 'grammar_articles',
    enunciado: 'He ate ___ apple for lunch.',
    opciones: ['a', 'an', 'the', '(no article)'],
    correcta: 1,
    explicacion: 'Se usa "an" antes de sonido vocal. "Apple" empieza por vocal -> an apple.',
    dificultad: 1,
  },
  {
    categoria: 'grammar_articles',
    enunciado: 'Could you close ___ door, please?',
    opciones: ['a', 'an', 'the', '(no article)'],
    correcta: 2,
    explicacion: 'Se usa "the" cuando ambos interlocutores saben de que puerta se habla (especifica).',
    dificultad: 1,
  },
  {
    categoria: 'grammar_articles',
    enunciado: 'It is ___ honest mistake.',
    opciones: ['a', 'an', 'the', '(no article)'],
    correcta: 1,
    explicacion: '"Honest" empieza con sonido vocal (la "h" es muda) -> an honest mistake.',
    dificultad: 1,
  },
  {
    categoria: 'grammar_articles',
    enunciado: 'I need ___ umbrella. It\'s raining.',
    opciones: ['a', 'an', 'the', '(no article)'],
    correcta: 1,
    explicacion: '"Umbrella" empieza por sonido vocal -> an umbrella.',
    dificultad: 1,
  },
  // Dificultad 2 — Zero article
  {
    categoria: 'grammar_articles',
    enunciado: 'I like ___ music.',
    opciones: ['a', 'an', 'the', '(no article)'],
    correcta: 3,
    explicacion: 'No se usa articulo con sustantivos incontables en sentido general: I like music.',
    dificultad: 2,
  },
  {
    categoria: 'grammar_articles',
    enunciado: '___ dogs are loyal animals.',
    opciones: ['A', 'An', 'The', '(no article)'],
    correcta: 3,
    explicacion: 'No se usa articulo con plurales en sentido general: Dogs (en general) are loyal.',
    dificultad: 2,
  },
  {
    categoria: 'grammar_articles',
    enunciado: 'She goes to ___ school by bus.',
    opciones: ['a', 'the', 'an', '(no article)'],
    correcta: 3,
    explicacion: 'No se usa articulo cuando "school" se refiere a la actividad (estudiar), no al edificio.',
    dificultad: 2,
  },
  {
    categoria: 'grammar_articles',
    enunciado: 'He had ___ breakfast at 7 AM.',
    opciones: ['a', 'an', 'the', '(no article)'],
    correcta: 3,
    explicacion: 'Las comidas no llevan articulo en ingles: have breakfast, have lunch, have dinner.',
    dificultad: 2,
  },
  {
    categoria: 'grammar_articles',
    enunciado: '___ life is beautiful.',
    opciones: ['A', 'An', 'The', '(no article)'],
    correcta: 3,
    explicacion: 'Conceptos abstractos en general no llevan articulo: Life (la vida en general).',
    dificultad: 2,
  },
  // Dificultad 3 — The with unique nouns, nationalities
  {
    categoria: 'grammar_articles',
    enunciado: '___ sun rises in the east.',
    opciones: ['A', 'An', 'The', '(no article)'],
    correcta: 2,
    explicacion: 'Se usa "the" con sustantivos unicos: the sun, the moon, the earth.',
    dificultad: 3,
  },
  {
    categoria: 'grammar_articles',
    enunciado: '___ Spanish are known for their hospitality.',
    opciones: ['A', 'An', 'The', '(no article)'],
    correcta: 2,
    explicacion: 'Se usa "the" + adjetivo de nacionalidad para referirse al pueblo: the Spanish = los espanoles.',
    dificultad: 3,
  },
  {
    categoria: 'grammar_articles',
    enunciado: 'He plays ___ piano very well.',
    opciones: ['a', 'an', 'the', '(no article)'],
    correcta: 2,
    explicacion: 'Se usa "the" con instrumentos musicales: play the piano, the guitar.',
    dificultad: 3,
  },
  {
    categoria: 'grammar_articles',
    enunciado: '___ Mount Everest is the highest mountain in the world.',
    opciones: ['A', 'An', 'The', '(no article)'],
    correcta: 3,
    explicacion: 'No se usa articulo con nombres de montanas individuales: Mount Everest (sin "the").',
    dificultad: 3,
  },
  {
    categoria: 'grammar_articles',
    enunciado: 'We visited ___ United Kingdom last summer.',
    opciones: ['a', 'an', 'the', '(no article)'],
    correcta: 2,
    explicacion: 'Se usa "the" con paises que incluyen una palabra como Kingdom, Republic, States: the United Kingdom.',
    dificultad: 3,
  },
]

// ---------------------------------------------------------------------------
// grammar_comparatives (~15 items)
// ---------------------------------------------------------------------------
const grammarComparatives: InglesItem[] = [
  // Dificultad 1 — -er/-est
  {
    categoria: 'grammar_comparatives',
    enunciado: 'My sister is ___ than me.',
    opciones: ['taller', 'more tall', 'tallest', 'most tall'],
    correcta: 0,
    explicacion: 'Adjetivos cortos (1 silaba): se anade -er para el comparativo. Tall -> taller.',
    dificultad: 1,
  },
  {
    categoria: 'grammar_comparatives',
    enunciado: 'This is the ___ building in the city.',
    opciones: ['taller', 'tallest', 'most tall', 'more tall'],
    correcta: 1,
    explicacion: 'Superlativo de adjetivos cortos: the + adj-est. Tall -> the tallest.',
    dificultad: 1,
  },
  {
    categoria: 'grammar_comparatives',
    enunciado: 'Summer is ___ than winter.',
    opciones: ['hot', 'hoter', 'hotter', 'hottest'],
    correcta: 2,
    explicacion: 'Adjetivos cortos CVC (consonante-vocal-consonante): se duplica la ultima consonante. Hot -> hotter.',
    dificultad: 1,
  },
  {
    categoria: 'grammar_comparatives',
    enunciado: 'Today is ___ than yesterday.',
    opciones: ['cold', 'colder', 'coldest', 'more cold'],
    correcta: 1,
    explicacion: 'Comparativo de "cold" (1 silaba): colder.',
    dificultad: 1,
  },
  {
    categoria: 'grammar_comparatives',
    enunciado: 'She is the ___ girl in the class.',
    opciones: ['young', 'younger', 'youngest', 'more young'],
    correcta: 2,
    explicacion: 'Superlativo de "young": the youngest.',
    dificultad: 1,
  },
  // Dificultad 2 — more/most + irregulares
  {
    categoria: 'grammar_comparatives',
    enunciado: 'This exercise is ___ than the last one.',
    opciones: ['difficulter', 'more difficult', 'most difficult', 'difficultest'],
    correcta: 1,
    explicacion: 'Adjetivos largos (3+ silabas) usan "more" para comparativo: more difficult.',
    dificultad: 2,
  },
  {
    categoria: 'grammar_comparatives',
    enunciado: 'His English is ___ than mine.',
    opciones: ['gooder', 'more good', 'better', 'best'],
    correcta: 2,
    explicacion: '"Good" es irregular: good -> better -> best.',
    dificultad: 2,
  },
  {
    categoria: 'grammar_comparatives',
    enunciado: 'The situation is getting ___.',
    opciones: ['badder', 'worse', 'more bad', 'worst'],
    correcta: 1,
    explicacion: '"Bad" es irregular: bad -> worse -> worst.',
    dificultad: 2,
  },
  {
    categoria: 'grammar_comparatives',
    enunciado: 'This is the ___ interesting book I\'ve ever read.',
    opciones: ['more', 'most', 'much', 'many'],
    correcta: 1,
    explicacion: 'Superlativo de adjetivos largos: the most + adjetivo. The most interesting.',
    dificultad: 2,
  },
  {
    categoria: 'grammar_comparatives',
    enunciado: 'She speaks English ___ than her brother.',
    opciones: ['more fluently', 'fluentlier', 'most fluently', 'fluently'],
    correcta: 0,
    explicacion: 'Adverbios largos (terminados en -ly): more + adverbio. More fluently.',
    dificultad: 2,
  },
  // Dificultad 3 — as...as, less...than, superlatives
  {
    categoria: 'grammar_comparatives',
    enunciado: 'He is not ___ tall ___ his father.',
    opciones: ['as / as', 'so / than', 'more / as', 'as / than'],
    correcta: 0,
    explicacion: 'Igualdad negada: not as + adj + as. "He is not as tall as his father."',
    dificultad: 3,
  },
  {
    categoria: 'grammar_comparatives',
    enunciado: 'This hotel is ___ expensive than the other one.',
    opciones: ['more', 'less', 'least', 'fewer'],
    correcta: 1,
    explicacion: '"Less" = menos. Comparativo de inferioridad: less expensive than.',
    dificultad: 3,
  },
  {
    categoria: 'grammar_comparatives',
    enunciado: 'Of all the students, she works ___.',
    opciones: ['harder', 'the hardest', 'more hard', 'hardest'],
    correcta: 1,
    explicacion: '"Of all" indica superlativo con grupo completo: the hardest.',
    dificultad: 3,
  },
  {
    categoria: 'grammar_comparatives',
    enunciado: 'The ___ you study, the ___ you will learn.',
    opciones: ['more / more', 'most / most', 'more / most', 'much / much'],
    correcta: 0,
    explicacion: 'Estructura "The more... the more..." expresa proporcion: cuanto mas... mas...',
    dificultad: 3,
  },
  {
    categoria: 'grammar_comparatives',
    enunciado: 'This is by far the ___ option of all.',
    opciones: ['worse', 'worst', 'bad', 'more bad'],
    correcta: 1,
    explicacion: '"By far the + superlativo" enfatiza el grado maximo. Bad -> worst.',
    dificultad: 3,
  },
]

// ---------------------------------------------------------------------------
// grammar_modals (~15 items)
// ---------------------------------------------------------------------------
const grammarModals: InglesItem[] = [
  // Dificultad 1 — can/can't, must/mustn't
  {
    categoria: 'grammar_modals',
    enunciado: 'You ___ park here. It\'s a no-parking zone.',
    opciones: ['can', 'can\'t', 'must', 'should'],
    correcta: 1,
    explicacion: '"Can\'t" expresa prohibicion. No-parking zone = no puedes aparcar.',
    dificultad: 1,
  },
  {
    categoria: 'grammar_modals',
    enunciado: 'She ___ speak three languages.',
    opciones: ['can', 'must', 'should', 'has'],
    correcta: 0,
    explicacion: '"Can" expresa habilidad. She can speak = ella sabe/puede hablar.',
    dificultad: 1,
  },
  {
    categoria: 'grammar_modals',
    enunciado: 'You ___ wear a uniform at this school.',
    opciones: ['can', 'can\'t', 'must', 'might'],
    correcta: 2,
    explicacion: '"Must" expresa obligacion. Es obligatorio llevar uniforme.',
    dificultad: 1,
  },
  {
    categoria: 'grammar_modals',
    enunciado: 'You ___ touch that. It\'s dangerous!',
    opciones: ['must', 'can', 'mustn\'t', 'should'],
    correcta: 2,
    explicacion: '"Mustn\'t" = no debes, esta prohibido. Expresa prohibicion fuerte.',
    dificultad: 1,
  },
  {
    categoria: 'grammar_modals',
    enunciado: '___ I use your phone?',
    opciones: ['Must', 'Should', 'Can', 'Will'],
    correcta: 2,
    explicacion: '"Can I...?" se usa para pedir permiso de forma informal.',
    dificultad: 1,
  },
  // Dificultad 2 — should/shouldn't, have to
  {
    categoria: 'grammar_modals',
    enunciado: 'You look tired. You ___ go to bed early tonight.',
    opciones: ['must', 'should', 'can', 'might'],
    correcta: 1,
    explicacion: '"Should" expresa consejo. Es mas suave que "must".',
    dificultad: 2,
  },
  {
    categoria: 'grammar_modals',
    enunciado: 'I ___ go to work tomorrow. It\'s a public holiday.',
    opciones: ['don\'t have to', 'mustn\'t', 'can\'t', 'shouldn\'t'],
    correcta: 0,
    explicacion: '"Don\'t have to" = no es necesario (no hay obligacion). "Mustn\'t" = esta prohibido.',
    dificultad: 2,
  },
  {
    categoria: 'grammar_modals',
    enunciado: 'You ___ eat so much sugar. It\'s bad for you.',
    opciones: ['mustn\'t', 'shouldn\'t', 'don\'t have to', 'can\'t'],
    correcta: 1,
    explicacion: '"Shouldn\'t" = no deberias (consejo). "Mustn\'t" seria prohibicion mas fuerte.',
    dificultad: 2,
  },
  {
    categoria: 'grammar_modals',
    enunciado: 'She ___ work on Saturdays. It\'s part of her contract.',
    opciones: ['should', 'might', 'has to', 'can'],
    correcta: 2,
    explicacion: '"Has to" (3a persona) = obligacion externa (impuesta por contrato, ley, etc.).',
    dificultad: 2,
  },
  {
    categoria: 'grammar_modals',
    enunciado: 'You ___ drive without a licence. It\'s illegal.',
    opciones: ['shouldn\'t', 'mustn\'t', 'don\'t have to', 'needn\'t'],
    correcta: 1,
    explicacion: '"Mustn\'t" = prohibicion. Conducir sin carnet es ilegal, no solo un consejo.',
    dificultad: 2,
  },
  // Dificultad 3 — might/could, needn't vs mustn't
  {
    categoria: 'grammar_modals',
    enunciado: 'It ___ rain later. Take an umbrella just in case.',
    opciones: ['must', 'will', 'might', 'should'],
    correcta: 2,
    explicacion: '"Might" expresa posibilidad (quiza llueva). No es seguro.',
    dificultad: 3,
  },
  {
    categoria: 'grammar_modals',
    enunciado: 'You ___ buy a ticket. I\'ve already got one for you.',
    opciones: ['mustn\'t', 'needn\'t', 'can\'t', 'shouldn\'t'],
    correcta: 1,
    explicacion: '"Needn\'t" = no necesitas, no es necesario. "Mustn\'t" = prohibicion (diferente significado).',
    dificultad: 3,
  },
  {
    categoria: 'grammar_modals',
    enunciado: 'She ___ be at home. Her lights are on.',
    opciones: ['can', 'could', 'must', 'should'],
    correcta: 2,
    explicacion: '"Must" para deduccion logica con alta certeza: las luces estan encendidas, asi que debe estar en casa.',
    dificultad: 3,
  },
  {
    categoria: 'grammar_modals',
    enunciado: 'He ___ have left already. His car is not in the driveway.',
    opciones: ['must', 'should', 'can', 'will'],
    correcta: 0,
    explicacion: '"Must have + past participle" = deduccion sobre el pasado: seguramente ya se fue.',
    dificultad: 3,
  },
  {
    categoria: 'grammar_modals',
    enunciado: 'When I was young, I ___ run very fast.',
    opciones: ['can', 'could', 'must', 'may'],
    correcta: 1,
    explicacion: '"Could" es el pasado de "can" para habilidades: cuando era joven, podia correr rapido.',
    dificultad: 3,
  },
]

// ---------------------------------------------------------------------------
// grammar_conditionals (~15 items)
// ---------------------------------------------------------------------------
const grammarConditionals: InglesItem[] = [
  // Dificultad 1 — Zero conditional
  {
    categoria: 'grammar_conditionals',
    enunciado: 'If you heat ice, it ___.',
    opciones: ['melts', 'melted', 'will melt', 'would melt'],
    correcta: 0,
    explicacion: 'Zero conditional (verdades universales): If + present, present. El hielo siempre se derrite.',
    dificultad: 1,
  },
  {
    categoria: 'grammar_conditionals',
    enunciado: 'If you mix red and blue, you ___ purple.',
    opciones: ['got', 'get', 'will get', 'would get'],
    correcta: 1,
    explicacion: 'Zero conditional: verdad universal. Rojo + azul siempre da morado.',
    dificultad: 1,
  },
  {
    categoria: 'grammar_conditionals',
    enunciado: 'Plants die if they ___ enough water.',
    opciones: ['don\'t get', 'didn\'t get', 'won\'t get', 'wouldn\'t get'],
    correcta: 0,
    explicacion: 'Zero conditional: If + present simple, present simple. Hecho general.',
    dificultad: 1,
  },
  {
    categoria: 'grammar_conditionals',
    enunciado: 'If it rains, the ground ___ wet.',
    opciones: ['gets', 'got', 'will get', 'would get'],
    correcta: 0,
    explicacion: 'Zero conditional para hechos generales: present + present.',
    dificultad: 1,
  },
  {
    categoria: 'grammar_conditionals',
    enunciado: 'Water ___ if you heat it to 100 degrees.',
    opciones: ['boils', 'boiled', 'will boil', 'would boil'],
    correcta: 0,
    explicacion: 'Zero conditional: hecho cientifico. Present simple en ambas clausulas.',
    dificultad: 1,
  },
  // Dificultad 2 — First conditional
  {
    categoria: 'grammar_conditionals',
    enunciado: 'If it rains tomorrow, I ___ at home.',
    opciones: ['stay', 'stayed', 'will stay', 'would stay'],
    correcta: 2,
    explicacion: 'First conditional (situacion real futura): If + present, will + infinitivo.',
    dificultad: 2,
  },
  {
    categoria: 'grammar_conditionals',
    enunciado: 'If you study hard, you ___ the exam.',
    opciones: ['pass', 'passed', 'will pass', 'would pass'],
    correcta: 2,
    explicacion: 'First conditional: situacion probable futura. If + present, will + infinitivo.',
    dificultad: 2,
  },
  {
    categoria: 'grammar_conditionals',
    enunciado: 'I ___ you if I need help.',
    opciones: ['call', 'called', 'will call', 'would call'],
    correcta: 2,
    explicacion: 'First conditional: If + present, will + infinitivo. "I will call you if I need help."',
    dificultad: 2,
  },
  {
    categoria: 'grammar_conditionals',
    enunciado: 'If she ___ late, we will start without her.',
    opciones: ['is', 'was', 'will be', 'would be'],
    correcta: 0,
    explicacion: 'First conditional: la clausula con "if" usa present simple, NO "will". If she is late...',
    dificultad: 2,
  },
  {
    categoria: 'grammar_conditionals',
    enunciado: 'We won\'t go to the park if the weather ___ bad.',
    opciones: ['is', 'was', 'will be', 'would be'],
    correcta: 0,
    explicacion: 'First conditional: present simple despues de "if". If the weather is bad...',
    dificultad: 2,
  },
  // Dificultad 3 — Second conditional
  {
    categoria: 'grammar_conditionals',
    enunciado: 'If I were rich, I ___ around the world.',
    opciones: ['travel', 'travelled', 'will travel', 'would travel'],
    correcta: 3,
    explicacion: 'Second conditional (situacion hipotetica/irreal): If + past simple, would + infinitivo.',
    dificultad: 3,
  },
  {
    categoria: 'grammar_conditionals',
    enunciado: 'If I ___ you, I would accept the offer.',
    opciones: ['am', 'was', 'were', 'will be'],
    correcta: 2,
    explicacion: 'Second conditional: se usa "were" para todas las personas en registro formal. "If I were you..."',
    dificultad: 3,
  },
  {
    categoria: 'grammar_conditionals',
    enunciado: 'What would you do if you ___ the lottery?',
    opciones: ['win', 'won', 'will win', 'have won'],
    correcta: 1,
    explicacion: 'Second conditional: If + past simple. "If you won the lottery" (situacion hipotetica).',
    dificultad: 3,
  },
  {
    categoria: 'grammar_conditionals',
    enunciado: 'If he ___ harder, he would pass the exam.',
    opciones: ['studies', 'studied', 'will study', 'would study'],
    correcta: 1,
    explicacion: 'Second conditional: If + past simple, would + infinitivo. Situacion irreal/hipotetica.',
    dificultad: 3,
  },
  {
    categoria: 'grammar_conditionals',
    enunciado: 'She ___ happier if she had more free time.',
    opciones: ['is', 'was', 'will be', 'would be'],
    correcta: 3,
    explicacion: 'Second conditional: would + infinitivo en la clausula principal.',
    dificultad: 3,
  },
]

// ---------------------------------------------------------------------------
// vocabulary_police (~20 items)
// ---------------------------------------------------------------------------
const vocabularyPolice: InglesItem[] = [
  // Dificultad 1 — Basic terms
  {
    categoria: 'vocabulary_police',
    enunciado: 'The officer ___ the suspect at the scene of the crime.',
    opciones: ['arrested', 'judged', 'sentenced', 'witnessed'],
    correcta: 0,
    explicacion: '"Arrest" = detener/arrestar a alguien. El policia detuvo al sospechoso en la escena del crimen.',
    dificultad: 1,
  },
  {
    categoria: 'vocabulary_police',
    enunciado: 'The police found important ___ at the crime scene.',
    opciones: ['verdict', 'evidence', 'bail', 'sentence'],
    correcta: 1,
    explicacion: '"Evidence" = pruebas/evidencia. La policia encontro pruebas en la escena del crimen.',
    dificultad: 1,
  },
  {
    categoria: 'vocabulary_police',
    enunciado: 'A ___ is a person who the police think committed a crime.',
    opciones: ['witness', 'victim', 'suspect', 'judge'],
    correcta: 2,
    explicacion: '"Suspect" = sospechoso. Persona que la policia cree que cometio un delito.',
    dificultad: 1,
  },
  {
    categoria: 'vocabulary_police',
    enunciado: 'Two officers were sent on ___ in the neighbourhood.',
    opciones: ['patrol', 'trial', 'custody', 'verdict'],
    correcta: 0,
    explicacion: '"Patrol" = patrulla. Los agentes fueron a patrullar el barrio.',
    dificultad: 1,
  },
  {
    categoria: 'vocabulary_police',
    enunciado: 'The ___ reported the robbery to the police immediately.',
    opciones: ['criminal', 'suspect', 'victim', 'prisoner'],
    correcta: 2,
    explicacion: '"Victim" = victima. La persona afectada por el delito denuncio el robo.',
    dificultad: 1,
  },
  {
    categoria: 'vocabulary_police',
    enunciado: 'Stealing from a shop is called ___.',
    opciones: ['assault', 'shoplifting', 'fraud', 'arson'],
    correcta: 1,
    explicacion: '"Shoplifting" = hurto en tienda. Robar productos de una tienda.',
    dificultad: 1,
  },
  {
    categoria: 'vocabulary_police',
    enunciado: 'A person who sees a crime happen is called a ___.',
    opciones: ['suspect', 'witness', 'victim', 'detective'],
    correcta: 1,
    explicacion: '"Witness" = testigo. Persona que presencia un delito.',
    dificultad: 1,
  },
  // Dificultad 2 — Legal terms
  {
    categoria: 'vocabulary_police',
    enunciado: 'The suspect was taken into police ___.',
    opciones: ['custody', 'sentence', 'verdict', 'bail'],
    correcta: 0,
    explicacion: '"Custody" = custodia. Estar bajo custodia policial = detenido.',
    dificultad: 2,
  },
  {
    categoria: 'vocabulary_police',
    enunciado: 'The judge granted ___, and the suspect was released.',
    opciones: ['evidence', 'bail', 'custody', 'patrol'],
    correcta: 1,
    explicacion: '"Bail" = fianza. El juez concedio la libertad bajo fianza.',
    dificultad: 2,
  },
  {
    categoria: 'vocabulary_police',
    enunciado: 'The ___ was five years in prison.',
    opciones: ['witness', 'arrest', 'sentence', 'patrol'],
    correcta: 2,
    explicacion: '"Sentence" = condena/sentencia. La condena fue de cinco anos de prision.',
    dificultad: 2,
  },
  {
    categoria: 'vocabulary_police',
    enunciado: 'The jury reached a ___ of "not guilty".',
    opciones: ['sentence', 'verdict', 'arrest', 'custody'],
    correcta: 1,
    explicacion: '"Verdict" = veredicto. El jurado llego a un veredicto de "no culpable".',
    dificultad: 2,
  },
  {
    categoria: 'vocabulary_police',
    enunciado: 'The case will go to ___ next month.',
    opciones: ['patrol', 'trial', 'bail', 'custody'],
    correcta: 1,
    explicacion: '"Trial" = juicio. El caso ira a juicio el mes que viene.',
    dificultad: 2,
  },
  {
    categoria: 'vocabulary_police',
    enunciado: 'The defendant pleaded ___ to all charges.',
    opciones: ['evidence', 'bail', 'guilty', 'custody'],
    correcta: 2,
    explicacion: '"Plead guilty" = declararse culpable. El acusado se declaro culpable de todos los cargos.',
    dificultad: 2,
  },
  {
    categoria: 'vocabulary_police',
    enunciado: 'The ___ questioned the suspect for three hours.',
    opciones: ['witness', 'victim', 'detective', 'prisoner'],
    correcta: 2,
    explicacion: '"Detective" = detective/investigador. El detective interrogo al sospechoso.',
    dificultad: 2,
  },
  // Dificultad 3 — Technical terms
  {
    categoria: 'vocabulary_police',
    enunciado: 'The ___ team collected DNA samples from the scene.',
    opciones: ['patrol', 'forensic', 'custody', 'verdict'],
    correcta: 1,
    explicacion: '"Forensic" = forense. El equipo forense recogio muestras de ADN.',
    dificultad: 3,
  },
  {
    categoria: 'vocabulary_police',
    enunciado: 'The police set up ___ cameras around the building.',
    opciones: ['custody', 'verdict', 'surveillance', 'bail'],
    correcta: 2,
    explicacion: '"Surveillance" = vigilancia. Camaras de vigilancia alrededor del edificio.',
    dificultad: 3,
  },
  {
    categoria: 'vocabulary_police',
    enunciado: 'This crime falls outside our ___. Contact the state police.',
    opciones: ['warrant', 'forensics', 'jurisdiction', 'custody'],
    correcta: 2,
    explicacion: '"Jurisdiction" = jurisdiccion. El delito queda fuera de nuestra competencia territorial.',
    dificultad: 3,
  },
  {
    categoria: 'vocabulary_police',
    enunciado: 'The judge signed a search ___ for the house.',
    opciones: ['verdict', 'warrant', 'bail', 'sentence'],
    correcta: 1,
    explicacion: '"Warrant" = orden judicial. Una "search warrant" es una orden de registro.',
    dificultad: 3,
  },
  {
    categoria: 'vocabulary_police',
    enunciado: 'The witness gave a ___ at the police station.',
    opciones: ['verdict', 'warrant', 'statement', 'bail'],
    correcta: 2,
    explicacion: '"Statement" = declaracion. El testigo presto declaracion en comisaria.',
    dificultad: 3,
  },
  {
    categoria: 'vocabulary_police',
    enunciado: 'The officer was working ___. Nobody knew he was a policeman.',
    opciones: ['on patrol', 'undercover', 'on bail', 'in custody'],
    correcta: 1,
    explicacion: '"Undercover" = encubierto. El agente trabajaba de incognito.',
    dificultad: 3,
  },
]

// ---------------------------------------------------------------------------
// vocabulary_general (~15 items)
// ---------------------------------------------------------------------------
const vocabularyGeneral: InglesItem[] = [
  // Dificultad 1 — Common collocations
  {
    categoria: 'vocabulary_general',
    enunciado: 'I need to ___ my homework before dinner.',
    opciones: ['make', 'do', 'take', 'have'],
    correcta: 1,
    explicacion: '"Do homework" es la colocacion correcta. "Make" se usa con cosas que se crean (make a cake, make a decision).',
    dificultad: 1,
  },
  {
    categoria: 'vocabulary_general',
    enunciado: 'Can you ___ a photo of us, please?',
    opciones: ['make', 'do', 'take', 'give'],
    correcta: 2,
    explicacion: '"Take a photo" es la colocacion correcta. No se dice "make a photo" en ingles.',
    dificultad: 1,
  },
  {
    categoria: 'vocabulary_general',
    enunciado: 'She ___ a lot of money in her new job.',
    opciones: ['does', 'makes', 'takes', 'wins'],
    correcta: 1,
    explicacion: '"Make money" = ganar dinero (como salario). "Win money" seria ganar en un juego/loteria.',
    dificultad: 1,
  },
  {
    categoria: 'vocabulary_general',
    enunciado: 'Let\'s ___ a break. I\'m tired.',
    opciones: ['do', 'make', 'have', 'give'],
    correcta: 2,
    explicacion: '"Have a break" = tomar un descanso. Tambien es correcto "take a break".',
    dificultad: 1,
  },
  {
    categoria: 'vocabulary_general',
    enunciado: 'She ___ a mistake on the test.',
    opciones: ['did', 'made', 'took', 'had'],
    correcta: 1,
    explicacion: '"Make a mistake" = cometer un error. Es una colocacion fija.',
    dificultad: 1,
  },
  // Dificultad 2 — Confusing pairs
  {
    categoria: 'vocabulary_general',
    enunciado: 'Can I ___ your pen for a moment?',
    opciones: ['borrow', 'lend', 'give', 'steal'],
    correcta: 0,
    explicacion: '"Borrow" = tomar prestado (tu recibes). "Lend" = prestar (tu das). "Can I borrow...?" = ¿me prestas...?',
    dificultad: 2,
  },
  {
    categoria: 'vocabulary_general',
    enunciado: 'He ___ me that he was leaving.',
    opciones: ['said', 'told', 'spoke', 'talked'],
    correcta: 1,
    explicacion: '"Tell + persona": He told me. "Say" no lleva persona directamente: He said (that) he was leaving.',
    dificultad: 2,
  },
  {
    categoria: 'vocabulary_general',
    enunciado: 'Please ___ here. Don\'t go away.',
    opciones: ['come', 'go', 'bring', 'take'],
    correcta: 0,
    explicacion: '"Come" = venir (hacia el hablante). "Go" = ir (lejos del hablante). "Come here" = ven aqui.',
    dificultad: 2,
  },
  {
    categoria: 'vocabulary_general',
    enunciado: 'Don\'t forget to ___ your umbrella. It\'s raining.',
    opciones: ['take', 'bring', 'carry', 'hold'],
    correcta: 1,
    explicacion: '"Bring" = traer (hacia donde estamos). "Take" = llevar (lejos). Aqui se pide que lo traiga consigo.',
    dificultad: 2,
  },
  {
    categoria: 'vocabulary_general',
    enunciado: 'I ___ with the decision. I think it was wrong.',
    opciones: ['agree', 'disagree', 'deny', 'refuse'],
    correcta: 1,
    explicacion: '"Disagree with" = no estar de acuerdo con. "Deny" = negar un hecho. "Refuse" = rechazar/negarse.',
    dificultad: 2,
  },
  // Dificultad 3 — False friends and idioms
  {
    categoria: 'vocabulary_general',
    enunciado: 'I am very ___ about the trip to London.',
    opciones: ['excited', 'exciting', 'exited', 'exitant'],
    correcta: 0,
    explicacion: '"Excited" (emocionado) para personas. "Exciting" para cosas/eventos. Falso amigo: "exitoso" en espanol = "successful" en ingles.',
    dificultad: 3,
  },
  {
    categoria: 'vocabulary_general',
    enunciado: 'I ___ going to the cinema tonight.',
    opciones: ['pretend', 'intend', 'want', 'feel like'],
    correcta: 3,
    explicacion: '"Feel like" + gerundio = tener ganas de. Falso amigo: "pretend" = fingir (NO "pretender" en espanol).',
    dificultad: 3,
  },
  {
    categoria: 'vocabulary_general',
    enunciado: 'She ___ her exam last week.',
    opciones: ['approved', 'passed', 'succeeded', 'overcame'],
    correcta: 1,
    explicacion: '"Pass an exam" = aprobar un examen. Falso amigo: "approve" = autorizar/dar el visto bueno.',
    dificultad: 3,
  },
  {
    categoria: 'vocabulary_general',
    enunciado: 'The conference was a great ___.',
    opciones: ['exit', 'success', 'assist', 'resume'],
    correcta: 1,
    explicacion: '"Success" = exito. Falsos amigos: "exit" = salida, "assist" = ayudar, "resume" = curriculum/reanudar.',
    dificultad: 3,
  },
  {
    categoria: 'vocabulary_general',
    enunciado: 'I ___ the university in 2018.',
    opciones: ['assisted', 'attended', 'frequented', 'assisted to'],
    correcta: 1,
    explicacion: '"Attend" = asistir a (un lugar/evento). Falso amigo: "assist" = ayudar (NO asistir).',
    dificultad: 3,
  },
]

// ---------------------------------------------------------------------------
// reading_comprehension (~20 items)
// ---------------------------------------------------------------------------
const readingComprehension: InglesItem[] = [
  // Dificultad 1 — Short factual texts
  {
    categoria: 'reading_comprehension',
    enunciado: 'Read the text:\n\n"John works at a hospital. He helps sick people every day. He wears a white coat and uses a stethoscope. He studied medicine for six years."\n\nWhat is John\'s job?',
    opciones: ['Nurse', 'Doctor', 'Pharmacist', 'Dentist'],
    correcta: 1,
    explicacion: 'Las pistas son: trabaja en un hospital, ayuda a enfermos, lleva bata blanca, usa estetoscopio y estudio medicina 6 anos -> es medico (doctor).',
    dificultad: 1,
  },
  {
    categoria: 'reading_comprehension',
    enunciado: 'Read the text:\n\n"The library opens at 9 AM and closes at 8 PM from Monday to Friday. On Saturdays, it opens at 10 AM and closes at 2 PM. It is closed on Sundays."\n\nWhen does the library close on Saturdays?',
    opciones: ['At 8 PM', 'At 2 PM', 'At 10 AM', 'It is closed'],
    correcta: 1,
    explicacion: 'El texto dice claramente: "On Saturdays, it opens at 10 AM and closes at 2 PM."',
    dificultad: 1,
  },
  {
    categoria: 'reading_comprehension',
    enunciado: 'Read the text:\n\n"Maria is from Spain. She moved to London three years ago. She works as a teacher at a primary school. She teaches Spanish to English children."\n\nWhat does Maria teach?',
    opciones: ['English', 'Mathematics', 'Spanish', 'Science'],
    correcta: 2,
    explicacion: 'El texto dice: "She teaches Spanish to English children." Ensena espanol.',
    dificultad: 1,
  },
  {
    categoria: 'reading_comprehension',
    enunciado: 'Read the text:\n\n"The train to Manchester leaves at 10:15 from Platform 3. Passengers must buy their tickets before boarding. The journey takes approximately two hours."\n\nHow long is the journey?',
    opciones: ['One hour', 'About two hours', 'Three hours', 'Fifteen minutes'],
    correcta: 1,
    explicacion: 'El texto dice: "The journey takes approximately two hours." Aproximadamente dos horas.',
    dificultad: 1,
  },
  {
    categoria: 'reading_comprehension',
    enunciado: 'Read the text:\n\n"Tom has two pets: a dog called Max and a cat called Bella. Max is five years old and Bella is three. Tom takes Max for a walk every morning."\n\nWhich pet is older?',
    opciones: ['Bella', 'Max', 'They are the same age', 'It doesn\'t say'],
    correcta: 1,
    explicacion: 'Max tiene 5 anos y Bella tiene 3, asi que Max es mayor.',
    dificultad: 1,
  },
  {
    categoria: 'reading_comprehension',
    enunciado: 'Read the text:\n\n"The supermarket is open from 8 AM to 10 PM every day. It sells food, drinks, cleaning products, and newspapers. There is a car park behind the building with space for 200 cars."\n\nWhat can you find behind the supermarket?',
    opciones: ['A park', 'A car park', 'A restaurant', 'A newspaper stand'],
    correcta: 1,
    explicacion: 'El texto dice: "There is a car park behind the building." Hay un aparcamiento detras.',
    dificultad: 1,
  },
  {
    categoria: 'reading_comprehension',
    enunciado: 'Read the text:\n\n"Sarah gets up at 7 AM. She has breakfast at 7:30 and leaves for work at 8:00. She works from 9 AM to 5 PM. After work, she goes to the gym."\n\nWhat time does Sarah leave for work?',
    opciones: ['At 7:00', 'At 7:30', 'At 8:00', 'At 9:00'],
    correcta: 2,
    explicacion: 'El texto dice: "leaves for work at 8:00". Sale de casa a las 8:00.',
    dificultad: 1,
  },
  // Dificultad 2 — Inference required
  {
    categoria: 'reading_comprehension',
    enunciado: 'Read the text:\n\n"Last summer, the Robinson family went to Italy for two weeks. They visited Rome, Florence, and Venice. Mr Robinson loved the food, especially the pizza. Mrs Robinson preferred the museums. Their children enjoyed the beaches the most."\n\nAccording to the text, what did the children like best?',
    opciones: ['The food', 'The museums', 'The beaches', 'The hotels'],
    correcta: 2,
    explicacion: '"Their children enjoyed the beaches the most." Los ninos disfrutaron mas de las playas.',
    dificultad: 2,
  },
  {
    categoria: 'reading_comprehension',
    enunciado: 'Read the text:\n\n"More and more people are working from home these days. Companies have found that employees can be just as productive at home as in the office. However, some workers miss the social contact with their colleagues and find it harder to separate work from personal life."\n\nWhat is a disadvantage of working from home mentioned in the text?',
    opciones: ['Lower productivity', 'Less social contact', 'Higher costs', 'Longer working hours'],
    correcta: 1,
    explicacion: 'El texto dice que algunos echan de menos el contacto social con companeros: "miss the social contact".',
    dificultad: 2,
  },
  {
    categoria: 'reading_comprehension',
    enunciado: 'Read the text:\n\n"David applied for a job at a bank last month. He had an interview on Tuesday and they called him on Friday to offer him the position. He was very happy because the salary was higher than in his previous job."\n\nWhat happened on Friday?',
    opciones: ['David applied for the job', 'David had an interview', 'David was offered the job', 'David started working'],
    correcta: 2,
    explicacion: '"They called him on Friday to offer him the position." Le ofrecieron el puesto el viernes.',
    dificultad: 2,
  },
  {
    categoria: 'reading_comprehension',
    enunciado: 'Read the text:\n\n"The new shopping centre has 150 shops, 20 restaurants, and a large cinema with 12 screens. It also has a free car park for 1,000 cars. Since it opened last month, over 50,000 people have visited it."\n\nHow many screens does the cinema have?',
    opciones: ['20', '150', '12', '1,000'],
    correcta: 2,
    explicacion: '"A large cinema with 12 screens." El cine tiene 12 pantallas.',
    dificultad: 2,
  },
  {
    categoria: 'reading_comprehension',
    enunciado: 'Read the text:\n\n"Electric cars are becoming more popular. They are better for the environment because they don\'t produce exhaust fumes. However, they are still more expensive than petrol cars and it can be difficult to find charging stations in some areas."\n\nWhy are electric cars better for the environment?',
    opciones: ['They are cheaper', 'They are faster', 'They don\'t produce exhaust fumes', 'They use less electricity'],
    correcta: 2,
    explicacion: '"They are better for the environment because they don\'t produce exhaust fumes." No producen gases de escape.',
    dificultad: 2,
  },
  {
    categoria: 'reading_comprehension',
    enunciado: 'Read the text:\n\n"Anna loves cooking. Last weekend, she made a chocolate cake for her mother\'s birthday. She spent three hours in the kitchen. When her mother tasted the cake, she said it was the best cake she had ever eaten."\n\nHow did Anna\'s mother feel about the cake?',
    opciones: ['She didn\'t like it', 'She thought it was the best ever', 'She preferred another cake', 'She didn\'t taste it'],
    correcta: 1,
    explicacion: '"She said it was the best cake she had ever eaten." Dijo que era el mejor pastel que habia probado.',
    dificultad: 2,
  },
  // Dificultad 3 — Complex texts, vocabulary in context
  {
    categoria: 'reading_comprehension',
    enunciado: 'Read the text:\n\n"The role of the police has changed significantly over the past century. While officers once focused mainly on enforcing laws and catching criminals, modern policing also involves community engagement, crime prevention, and the use of advanced technology such as body cameras and data analytics."\n\nAccording to the text, modern policing includes:',
    opciones: ['Only catching criminals', 'Less use of technology', 'Community engagement and crime prevention', 'Fewer responsibilities than before'],
    correcta: 2,
    explicacion: 'El texto menciona que la policia moderna incluye "community engagement, crime prevention, and the use of advanced technology".',
    dificultad: 3,
  },
  {
    categoria: 'reading_comprehension',
    enunciado: 'Read the text:\n\n"Despite being a small country, the Netherlands has one of the most efficient police forces in Europe. Officers undergo extensive training that includes conflict resolution, cultural sensitivity, and advanced driving skills. The emphasis on de-escalation techniques has led to fewer violent incidents."\n\nWhat has the focus on de-escalation achieved?',
    opciones: ['More arrests', 'Fewer violent incidents', 'Faster response times', 'Higher salaries'],
    correcta: 1,
    explicacion: '"The emphasis on de-escalation techniques has led to fewer violent incidents." Menos incidentes violentos.',
    dificultad: 3,
  },
  {
    categoria: 'reading_comprehension',
    enunciado: 'Read the text:\n\n"Cybercrime is one of the fastest-growing threats worldwide. Criminals use the internet to steal personal information, commit fraud, and attack computer systems. Law enforcement agencies have had to adapt by creating specialised units and hiring experts in information technology to combat these new forms of crime."\n\nWhat does the word "combat" mean in this context?',
    opciones: ['Support', 'Create', 'Fight against', 'Ignore'],
    correcta: 2,
    explicacion: '"Combat" = combatir/luchar contra. Las fuerzas del orden luchan contra nuevas formas de delito.',
    dificultad: 3,
  },
  {
    categoria: 'reading_comprehension',
    enunciado: 'Read the text:\n\n"Road safety campaigns have helped reduce the number of traffic accidents in Spain. The introduction of stricter penalties for drink-driving, speeding, and using mobile phones while driving has been particularly effective. However, distracted driving remains a significant problem, with many accidents caused by drivers who do not pay full attention to the road."\n\nWhat remains a significant problem according to the text?',
    opciones: ['Drink-driving', 'Speeding', 'Distracted driving', 'Strict penalties'],
    correcta: 2,
    explicacion: '"Distracted driving remains a significant problem." La conduccion distraida sigue siendo un problema significativo.',
    dificultad: 3,
  },
  {
    categoria: 'reading_comprehension',
    enunciado: 'Read the text:\n\n"First aid is an essential skill for police officers. They are often the first to arrive at the scene of an accident and must be able to provide basic medical assistance until an ambulance arrives. Training includes learning how to stop bleeding, perform CPR, and stabilise injured people."\n\nWhy is first aid important for police officers?',
    opciones: ['They replace doctors', 'They are often first at the scene', 'They work in hospitals', 'They drive ambulances'],
    correcta: 1,
    explicacion: '"They are often the first to arrive at the scene of an accident." Suelen ser los primeros en llegar al lugar del accidente.',
    dificultad: 3,
  },
  {
    categoria: 'reading_comprehension',
    enunciado: 'Read the text:\n\n"The European Union has established Europol to help member states fight serious international crime and terrorism. Europol does not have the power to arrest people directly; instead, it supports national police forces by sharing intelligence, coordinating operations, and providing expert analysis."\n\nWhat can we infer about Europol from the text?',
    opciones: ['It arrests criminals in all EU countries', 'It replaces national police forces', 'It is a support and coordination body', 'It only works against terrorism'],
    correcta: 2,
    explicacion: 'Europol no detiene directamente, sino que "supports national police forces" -> es un organismo de apoyo y coordinacion.',
    dificultad: 3,
  },
  {
    categoria: 'reading_comprehension',
    enunciado: 'Read the text:\n\n"Witness protection programmes are used to safeguard people who provide crucial testimony in criminal cases. These individuals may receive a new identity, be relocated to a different city, and given financial support. The programmes are controversial because of their high cost, but supporters argue they are essential for bringing dangerous criminals to justice."\n\nWhy are witness protection programmes controversial?',
    opciones: ['They are illegal', 'They cost a lot of money', 'Witnesses refuse to participate', 'They are not effective'],
    correcta: 1,
    explicacion: '"The programmes are controversial because of their high cost." Son controvertidos por su alto coste.',
    dificultad: 3,
  },
]

// ---------------------------------------------------------------------------
// Exportacion — banco completo
// ---------------------------------------------------------------------------
export const INGLES_BANK: readonly InglesItem[] = [
  ...grammarTenses,
  ...grammarPrepositions,
  ...grammarArticles,
  ...grammarComparatives,
  ...grammarModals,
  ...grammarConditionals,
  ...vocabularyPolice,
  ...vocabularyGeneral,
  ...readingComprehension,
] as const
